## ===================================== ##

# 01 Clinvar

## 1.1 Convert Clinvar txt data to excel

In [2]:
!ls 00_data/

clinvar_result.txt

In [6]:
import pandas as pd

# Load the tab-separated .txt file
df = pd.read_csv('00_data/clinvar_result.txt', sep='\t', low_memory=False)

# Save to Excel
df.to_excel('00_data/clinvar_result.xlsx', index=False)

In [15]:
import pandas as pd

# Load the Excel file and get sheet names
xls = pd.ExcelFile('00_data/clinvar_result.xlsx')
sheet_names = xls.sheet_names  # List of sheet names

# Load the first sheet (you can specify a different one)
df_excel = pd.read_excel(xls, sheet_name=sheet_names[0])

# Get column names
column_names = df_excel.columns

# Print sheet name and column names
print(f"Sheet Name: {sheet_names[0]}")
print("Column Names:", column_names)

Sheet Name: Sheet1
Column Names: Index(['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession',
       'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome',
       'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID',
       'Canonical SPDI', 'Variant type', 'Molecular consequence',
       'Germline classification', 'Germline date last evaluated',
       'Germline review status', 'Somatic clinical impact',
       'Somatic clinical impact date last evaluated',
       'Somatic clinical impact review status', 'Oncogenicity classification',
       'Oncogenicity date last evaluated', 'Oncogenicity review status',
       'Unnamed: 24'],
      dtype='object')

## 1.2 view 'Sheet1'

In [43]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='Sheet1')

# Display the dataset
display(df_excel)

,Name,Gene(s),Protein change,Condition(s),Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,...,Germline classification,Germline date last evaluated,Germline review status,Somatic clinical impact,Somatic clinical impact date last evaluated,Somatic clinical impact review status,Oncogenicity classification,Oncogenicity date last evaluated,Oncogenicity review status,Unnamed: 24
0,GRCh38/hg38 Xp22.33-q28(chrX:2757837-156030895)x2,ABCB7|ABCD1|ACE2|ACE2-DT|ACOT9|ACSL4|ACTRT1|AD...,NaN,Klinefelter syndrome,VCV003242589,NaN,NaN,X,2757837 - 156030895,3242589,...,Pathogenic,"Jun 20, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GRCh37/hg19 Xp22.33-q28(chrX:200855-155240074),ABCB7|ABCD1|ACE2|ACOT9|ACSL4|ACTRT1|ADGRG2|ADG...,NaN,Klinefelter syndrome,VCV002506546,X,200855 - 155240074,NaN,NaN,2506546,...,Pathogenic,"May 26, 2023","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GRCh37/hg19 Xp22.2-q28(chrX:11522765-155233731)x1,ABCB7|ABCD1|ACE2|ACOT9|ACSL4|ACTRT1|ADGRG2|ADG...,NaN,See cases,VCV001707442,X,11522765 - 155233731,NaN,NaN,1707442,...,Pathogenic,NaN,no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GRCh37/hg19 Xp22.33-q28(chrX:61545-155226048)x2,ABCB7|ABCD1|ACE2|ACOT9|ACSL4|ACTRT1|ADGRG2|ADG...,NaN,Klinefelter syndrome,VCV001704345,X,61545 - 155226048,NaN,NaN,1704345,...,Pathogenic,NaN,no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRCh37/hg19 Xp22.33-q28(chrX:1-155270560),ABCB7|ABCD1|ACE2|ACOT9|ACSL4|ACTRT1|ADGRG2|ADG...,NaN,Turner syndrome,VCV001703580,X,1 - 155270560,NaN,NaN,1703580,...,Pathogenic,NaN,no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2188,GRCh38/hg38 Xp22.33-11.22(chrX:10679-52213731)x1,TIMP1|TLR7|TLR8|TLR8-AS1|TMEM47|TMSB4X|TRAPPC2...,NaN,See cases,VCV000148018,X,60679 - 51948998,X,10679 - 52213731,148018,...,Pathogenic,"Dec 22, 2010",no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,GRCh37/hg19 Xp22.33-q28(chrX:71267-155224766)x1,TMEM185A|TMEM187|TMEM255A|TMEM31|TMEM35A|TMEM4...,NaN,See cases,VCV000253495,X,71267 - 155224766,NaN,NaN,253495,...,Pathogenic,"Jan 20, 2016","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2190,GRCh37/hg19 Xp22.33-q28(chrX:70297-155246585)x1,TMLHE|TMSB15A|TMSB15B|TMSB4X|TNMD|TRAPPC2|TREX...,NaN,See cases,VCV000395718,X,70297 - 155246585,NaN,NaN,395718,...,Pathogenic,NaN,no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2191,GRCh38/hg38 Xp22.33-11.22(chrX:10701-53750424)x1,USP27X|USP27X-DT|USP9X|UXT|UXT-AS1|VCX|VCX2|VC...,NaN,See cases,VCV000152052,X,60701 - 53776922,X,10701 - 53750424,152052,...,Pathogenic,"Nov 26, 2012",no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2192,GRCh37/hg19 Xp22.33-11.21(chrX:168546-57683964)x1,WDR45|WNK3|WWC3|ACE2|ACOT9|ADGRG2|AKAP4|ALAS2|...,NaN,See cases,VCV000441856,X,168546 - 57683964,NaN,NaN,441856,...,Pathogenic,"Jul 7, 2014",no assertion criteria provided,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1.3 show columns

In [46]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='Sheet1')

# Convert column names to DataFrame for better visualization
column_names_df = pd.DataFrame(df_excel.columns, columns=['Column Names'])

# Display the column names as a table
display(column_names_df)

                                   Column Names
0                                          Name
1                                       Gene(s)
2                                Protein change
3                                  Condition(s)
4                                     Accession
5                              GRCh37Chromosome
6                                GRCh37Location
7                              GRCh38Chromosome
8                                GRCh38Location
9                                   VariationID
10                                  AlleleID(s)
11                                     dbSNP ID
12                               Canonical SPDI
13                                 Variant type
14                        Molecular consequence
15                      Germline classification
16                 Germline date last evaluated
17                       Germline review status
18                      Somatic clinical impact
19  Somatic clinical impact date last evaluated
20        Somatic clinical impact review status
21                  Oncogenicity classification
22             Oncogenicity date last evaluated
23                   Oncogenicity review status
24                                  Unnamed: 24

### 1.4 Value counts: 'Sheet1':

In [62]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='Sheet1')

# Define columns to count
columns_to_count = ['Variant type', 'Condition(s)', 'Molecular consequence', 'Germline classification']

# Get value counts for each column and display them
for col in columns_to_count:
    counts_df = df_excel[col].value_counts().reset_index()
    counts_df.columns = [col, 'Count']
    
    # Add total count row
    total_row = pd.DataFrame([[f'Total {col}', counts_df['Count'].sum()]], columns=[col, 'Count'])
    counts_df = pd.concat([counts_df, total_row], ignore_index=True)

    # Display the table in IPython format
    display(counts_df)

                 Variant type  Count
0   single nucleotide variant   1517
1                    Deletion    269
2                 Duplication    139
3            copy number loss    107
4            copy number gain     78
5              Microsatellite     46
6                   Insertion     17
7                       Indel     16
8                     Complex      2
9                   Inversion      2
10         Total Variant type   2193

                                          Condition(s)  Count
0                                         not provided    578
1    Developmental and epileptic encephalopathy, 2|...    363
2    Angelman syndrome-like|Developmental and epile...    247
3                                       CDKL5 disorder    224
4                                            See cases    131
..                                                 ...    ...
148  Early infantile epileptic encephalopathy with ...      1
149  Developmental and epileptic encephalopathy, 2|...      1
150                                   Infantile spasms      1
151                        Neurodevelopmental disorder      1
152                                 Total Condition(s)   2193

[153 rows x 2 columns]

                           Molecular consequence  Count
0                               missense variant    485
1                missense variant|intron variant    301
2                                 intron variant    295
3                             frameshift variant    234
4                             synonymous variant    177
5                                       nonsense    101
6              synonymous variant|intron variant     97
7              frameshift variant|intron variant     49
8                        nonsense|intron variant     47
9                           splice donor variant     36
10                       splice acceptor variant     31
11                              inframe_deletion     10
12        intron variant|splice acceptor variant      8
13           intron variant|splice donor variant      7
14                           5 prime UTR variant      6
15                                 inframe_indel      5
16                  inframe_indel|intron variant      5
17            3 prime UTR variant|intron variant      4
18  splice acceptor variant|splice donor variant      3
19                      stop lost|intron variant      2
20    frameshift variant|nonsense|intron variant      2
21                    nonsense|inframe_insertion      1
22                             inframe_insertion      1
23           splice donor variant|intron variant      1
24         missense variant|splice donor variant      1
25                   Total Molecular consequence   1909

                         Germline classification  Count
0                                     Pathogenic    698
1                         Uncertain significance    473
2                                  Likely benign    471
3                              Likely pathogenic    229
4                                         Benign    112
5   Conflicting classifications of pathogenicity     68
6                   Pathogenic/Likely pathogenic     55
7                           Benign/Likely benign     44
8                                   not provided     42
9               conflicting data from submitters      1
10                 Total Germline classification   2193

## 1.5 Extract 'single nucleotide variant'from 'Variant type' and save as 'Single_Nucleotide_Variant' sheet

In [50]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
file_path = '00_data/clinvar_result.xlsx'
df_excel = pd.read_excel(file_path, sheet_name='Sheet1')

# Filter for 'single nucleotide variant' entries
snv_df = df_excel[df_excel['Variant type'] == 'single nucleotide variant']

# Load the workbook and write the new sheet without overwriting existing data
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl') as writer:
    snv_df.to_excel(writer, sheet_name='Single_Nucleotide_Variant', index=False)

print("Filtered data added as 'Single_Nucleotide_Variant' in the same Excel file.")

Filtered data added as 'Single_Nucleotide_Variant' in the same Excel file.

### 1.6 Value counts: 'Single_Nucleotid_variant' sheet

In [55]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='Single_Nucleotide_Variant')

# Filter rows containing 'missense' in 'Molecular consequence' column
missense_counts = df_excel[df_excel['Molecular consequence'].str.contains('missense variant', na=False)].shape[0]

# Display the count
print("Total occurrences of 'missense' in 'Molecular consequence' column:", missense_counts)

Total occurrences of 'missense' in 'Molecular consequence' column: 783

## 1.7 Extract 'missense variant' from 'Molecular Consequence' column

In [56]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
file_path = '00_data/clinvar_result.xlsx'
df_snv = pd.read_excel(file_path, sheet_name='Single_Nucleotide_Variant')

# Filter for 'missense variant' entries
missense_df = df_snv[df_snv['Molecular consequence'].str.contains('missense variant', na=False)]

# Load the workbook and write the new sheet without overwriting existing data
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl') as writer:
    missense_df.to_excel(writer, sheet_name='Missense_Variant', index=False)

print("Filtered data saved as 'Missense_Variant' in the same Excel file.")

Filtered data saved as 'Missense_Variant' in the same Excel file.

###  1.8 Value counts

In [58]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='Missense_Variant')

# Define columns to count
columns_to_count = ['Variant type', 'Condition(s)', 'Molecular consequence', 'Germline classification']

# Get value counts for each column and display them
for col in columns_to_count:
    counts_df = df_excel[col].value_counts().reset_index()
    counts_df.columns = [col, 'Count']
    
    # Add total count row
    total_row = pd.DataFrame([[f'Total {col}', counts_df['Count'].sum()]], columns=[col, 'Count'])
    counts_df = pd.concat([counts_df, total_row], ignore_index=True)

    # Display the table in IPython format
    display(counts_df)

                Variant type  Count
0  single nucleotide variant    783
1         Total Variant type    783

                                         Condition(s)  Count
0                                        not provided    205
1   Developmental and epileptic encephalopathy, 2|...    141
2   Angelman syndrome-like|Developmental and epile...     86
3                                      CDKL5 disorder     84
4       Developmental and epileptic encephalopathy, 2     33
..                                                ...    ...
79  not provided|CDKL5 disorder|Angelman syndrome-...      1
80  Inborn genetic diseases|Developmental and epil...      1
81  not provided|not specified|Angelman syndrome-l...      1
82  Retinoschisis|Retinal dystrophy|Juvenile retin...      1
83                                 Total Condition(s)    783

[84 rows x 2 columns]

                   Molecular consequence  Count
0                       missense variant    485
1        missense variant|intron variant    297
2  missense variant|splice donor variant      1
3            Total Molecular consequence    783

                        Germline classification  Count
0                        Uncertain significance    356
1                             Likely pathogenic    109
2                                    Pathogenic    103
3                                 Likely benign     72
4  Conflicting classifications of pathogenicity     50
5                  Pathogenic/Likely pathogenic     28
6                                        Benign     27
7                                  not provided     25
8                          Benign/Likely benign     13
9                 Total Germline classification    783

## 1.9 Extract 'CDKL5' from 'Condition(s)' column

In [59]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
file_path = '00_data/clinvar_result.xlsx'
df_missense = pd.read_excel(file_path, sheet_name='Missense_Variant')

# Filter rows containing 'CDKL5' in 'Condition(s)' column
cdkl5_df = df_missense[df_missense['Condition(s)'].str.contains('CDKL5', na=False)]

# Save the filtered data to a new sheet in the same Excel file
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl') as writer:
    cdkl5_df.to_excel(writer, sheet_name='CDKL5_Condition', index=False)

print("Filtered data saved as 'CDKL5_Condition' in the same Excel file.")

Filtered data saved as 'CDKL5_Condition' in the same Excel file.

### 1.10 Value counts

In [60]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_Condition')

# Define columns to count
columns_to_count = ['Variant type', 'Condition(s)', 'Molecular consequence', 'Germline classification']

# Get value counts for each column and display them
for col in columns_to_count:
    counts_df = df_excel[col].value_counts().reset_index()
    counts_df.columns = [col, 'Count']
    
    # Add total count row
    total_row = pd.DataFrame([[f'Total {col}', counts_df['Count'].sum()]], columns=[col, 'Count'])
    counts_df = pd.concat([counts_df, total_row], ignore_index=True)

    # Display the table in IPython format
    display(counts_df)

                Variant type  Count
0  single nucleotide variant    139
1         Total Variant type    139

                                         Condition(s)  Count
0                                      CDKL5 disorder     84
1   Developmental and epileptic encephalopathy, 2|...      7
2                         not provided|CDKL5 disorder      5
3   Angelman syndrome-like|Developmental and epile...      5
4                              CDKL5-related disorder      5
5   CDKL5 disorder|Developmental and epileptic enc...      4
6   CDKL5 disorder|Angelman syndrome-like|Developm...      4
7   Developmental and epileptic encephalopathy, 2|...      3
8              CDKL5 disorder|Inborn genetic diseases      2
9   CDKL5 disorder|not provided|Developmental and ...      2
10  Developmental and epileptic encephalopathy, 2|...      1
11  Developmental and epileptic encephalopathy, 2|...      1
12  Angelman syndrome-like|Developmental and epile...      1
13  Developmental and epileptic encephalopathy, 2|...      1
14  Epileptic encephalopathy|Developmental and epi...      1
15  CDKL5 disorder|Developmental and epileptic enc...      1
16  Angelman syndrome-like|Developmental and epile...      1
17  Developmental and epileptic encephalopathy, 2|...      1
18  Developmental and epileptic encephalopathy, 2|...      1
19  not specified|Developmental and epileptic ence...      1
20  CDKL5 disorder|not specified|not provided|Deve...      1
21  Inborn genetic diseases|CDKL5 disorder|not pro...      1
22  not provided|CDKL5 disorder|Angelman syndrome-...      1
23  CDKL5-related disorder|Developmental and epile...      1
24                CDKL5-related disorder|not provided      1
25  Angelman syndrome-like|Developmental and epile...      1
26  CDKL5 disorder|Developmental and epileptic enc...      1
27  West syndrome|Developmental and epileptic ence...      1
28                                 Total Condition(s)    139

             Molecular consequence  Count
0                 missense variant    120
1  missense variant|intron variant     19
2      Total Molecular consequence    139

                        Germline classification  Count
0                        Uncertain significance     45
1                             Likely pathogenic     22
2                                 Likely benign     19
3  Conflicting classifications of pathogenicity     16
4                                        Benign     16
5                                    Pathogenic      9
6                  Pathogenic/Likely pathogenic      8
7                          Benign/Likely benign      4
8                 Total Germline classification    139

## 1.11: only 'misssense variant' discard 'intron variant'

In [68]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
file_path = '00_data/clinvar_result.xlsx'
df_cdkl5_condition = pd.read_excel(file_path, sheet_name='CDKL5_Condition')

# Remove rows containing 'intron variant' in 'Molecular consequence' column
filtered_df = df_cdkl5_condition[~df_cdkl5_condition['Molecular consequence'].str.contains('intron variant', na=False)]

# Save the cleaned data to a new sheet with the correct name
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl') as writer:
    filtered_df.to_excel(writer, sheet_name='CDKL5_missense_only', index=False)

print("Filtered data saved as 'CDKL5_missense_only' in the same Excel file.")

Filtered data saved as 'CDKL5_missense_only' in the same Excel file.

### 1.12 Value count

In [69]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_excel = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_missense_only')

# Define columns to count
columns_to_count = ['Variant type', 'Condition(s)', 'Molecular consequence', 'Germline classification']

# Get value counts for each column and display them
for col in columns_to_count:
    counts_df = df_excel[col].value_counts().reset_index()
    counts_df.columns = [col, 'Count']
    
    # Add total count row
    total_row = pd.DataFrame([[f'Total {col}', counts_df['Count'].sum()]], columns=[col, 'Count'])
    counts_df = pd.concat([counts_df, total_row], ignore_index=True)

    # Display the table in IPython format
    display(counts_df)

                Variant type  Count
0  single nucleotide variant    120
1         Total Variant type    120

                                         Condition(s)  Count
0                                      CDKL5 disorder     74
1   Developmental and epileptic encephalopathy, 2|...      7
2                         not provided|CDKL5 disorder      5
3   Angelman syndrome-like|Developmental and epile...      5
4   CDKL5 disorder|Angelman syndrome-like|Developm...      4
5   CDKL5 disorder|Developmental and epileptic enc...      4
6                              CDKL5-related disorder      4
7   Developmental and epileptic encephalopathy, 2|...      2
8   CDKL5 disorder|not provided|Developmental and ...      2
9   CDKL5 disorder|Developmental and epileptic enc...      1
10  Angelman syndrome-like|Developmental and epile...      1
11  Developmental and epileptic encephalopathy, 2|...      1
12  Developmental and epileptic encephalopathy, 2|...      1
13  Epileptic encephalopathy|Developmental and epi...      1
14  Developmental and epileptic encephalopathy, 2|...      1
15  CDKL5 disorder|not specified|not provided|Deve...      1
16  Inborn genetic diseases|CDKL5 disorder|not pro...      1
17             CDKL5 disorder|Inborn genetic diseases      1
18  not provided|CDKL5 disorder|Angelman syndrome-...      1
19  CDKL5-related disorder|Developmental and epile...      1
20  CDKL5 disorder|Developmental and epileptic enc...      1
21  Angelman syndrome-like|Developmental and epile...      1
22                                 Total Condition(s)    120

         Molecular consequence  Count
0             missense variant    120
1  Total Molecular consequence    120

                        Germline classification  Count
0                        Uncertain significance     43
1                             Likely pathogenic     22
2  Conflicting classifications of pathogenicity     13
3                                        Benign     12
4                                 Likely benign     10
5                                    Pathogenic      9
6                  Pathogenic/Likely pathogenic      8
7                          Benign/Likely benign      3
8                 Total Germline classification    120

## 1.13 make 'Mutation' column with 'wild' 'position' 'mutant'

## =================================== ##

## 2 Comparison

### 2.1 Comparison: Unique common old vs new clinvar

In [64]:
import pandas as pd

# Load the two datasets
df_cdkl5_missense = pd.read_excel('00_data/clinvar_result_copy.xlsx', sheet_name='CDKL5_missense_AF')
df_cdkl5_condition = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_Condition')

# Extract 'Protein change' column from both datasets
protein_missense = set(df_cdkl5_missense['Protein change'].dropna())
protein_condition = set(df_cdkl5_condition['Protein change'].dropna())

# Find common and unique values
common_protein_changes = protein_missense.intersection(protein_condition)
unique_missense = protein_missense - protein_condition
unique_condition = protein_condition - protein_missense

# Convert results to DataFrames for saving
common_df = pd.DataFrame(list(common_protein_changes), columns=['Common Protein Changes'])
unique_missense_df = pd.DataFrame(list(unique_missense), columns=['Unique to CDKL5_missense_AF'])
unique_condition_df = pd.DataFrame(list(unique_condition), columns=['Unique to CDKL5_Condition'])

# Save comparisons in a new Excel file
comparison_file = "00_data/protein_change_comparison.xlsx"
with pd.ExcelWriter(comparison_file, mode='w', engine='openpyxl') as writer:
    common_df.to_excel(writer, sheet_name='Common_Protein_Changes', index=False)
    unique_missense_df.to_excel(writer, sheet_name='Unique_CDKL5_missense_AF', index=False)
    unique_condition_df.to_excel(writer, sheet_name='Unique_CDKL5_Condition', index=False)

print("Comparison results saved in 'protein_change_comparison.xlsx'.")

Comparison results saved in 'protein_change_comparison.xlsx'.

### 2.2 Comparison: Unique common old vs new clinvar after deleting 'intron variants'

In [73]:
import pandas as pd

# Load the two datasets
df_cdkl5_missense = pd.read_excel('00_data/clinvar_result_copy.xlsx', sheet_name='CDKL5_missense_AF')
df_cdkl5_missense_only = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_missense_only')

# Extract 'Protein change' column from both datasets
protein_missense = set(df_cdkl5_missense['Protein change'].dropna())
protein_missense_only = set(df_cdkl5_missense_only['Protein change'].dropna())

# Find common and unique values
common_protein_changes = protein_missense.intersection(protein_missense_only)
unique_missense = protein_missense - protein_missense_only
unique_missense_only = protein_missense_only - protein_missense

# Create a summary dictionary
summary = {
    'Total in CDKL5_missense_AF': len(protein_missense),
    'Total in CDKL5_missense_only': len(protein_missense_only),
    'Total Common': len(common_protein_changes),
    'Total Unique to CDKL5_missense_AF': len(unique_missense),
    'Total Unique to CDKL5_missense_only': len(unique_missense_only)
}

# Print the summary
print("\nComparison Summary:")
for key, value in summary.items():
    print(f"{key}: {value}")

# Convert results to DataFrames for saving
summary_df = pd.DataFrame(list(summary.items()), columns=['Category', 'Count'])
common_df = pd.DataFrame(list(common_protein_changes), columns=['Common Protein Changes'])
unique_missense_df = pd.DataFrame(list(unique_missense), columns=['Unique to CDKL5_missense_AF'])
unique_missense_only_df = pd.DataFrame(list(unique_missense_only), columns=['Unique to CDKL5_missense_only'])

# Save comparisons in a new Excel file
comparison_file = "00_data/protein_change_comparison.xlsx"
with pd.ExcelWriter(comparison_file, mode='w', engine='openpyxl') as writer:
    summary_df.to_excel(writer, sheet_name='Comparison_Summary', index=False)
    common_df.to_excel(writer, sheet_name='Common_Protein_Changes', index=False)
    unique_missense_df.to_excel(writer, sheet_name='Unique_CDKL5_missense_AF', index=False)
    unique_missense_only_df.to_excel(writer, sheet_name='Unique_CDKL5_missense_only', index=False)

print("\nComparison results saved in 'protein_change_comparison.xlsx'.")

Comparison Summary:
Total in CDKL5_missense_AF: 120
Total in CDKL5_missense_only: 120
Total Common: 120
Total Unique to CDKL5_missense_AF: 0
Total Unique to CDKL5_missense_only: 0

Comparison results saved in 'protein_change_comparison.xlsx'.

### 2.3 Comparison gnomAD vs Clinvar

#### 2.3.1 check clinvar sheets

In [13]:
import pandas as pd

# check sheet names
excel_file = '00_data/clinvar_result.xlsx'
sheet_names = pd.ExcelFile(excel_file).sheet_names

print(sheet_names)

['Sheet1', 'Single_Nucleotide_Variant', 'Missense_Variant', 'CDKL5_Condition', 'CDKL5_missense_only']

In [14]:
import pandas as pd

# Load a specific sheet
df = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name = 'CDKL5_missense_only')

print("Column names:", df.columns.tolist())

Column names: ['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24']

### 2.4 compare the 'Protein change' column 
from clinvar_result.xlsx and the 'Protein change (One-Letter)' column from gnomAD.xlsx, and print the number of common and unique entries in each:

In [30]:
import pandas as pd

# Load the ClinVar dataset
df1 = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_missense_only')

# Load the gnomAD dataset
df2 = pd.read_excel('00_data/gnomAD.xlsx', sheet_name='ClinVar_Classified_Only')

# Extract relevant columns and drop NaNs
set1 = set(df1['Protein change'].dropna().astype(str))
set2 = set(df2['Protein change (One-Letter)'].dropna().astype(str))

# Find common and unique elements
common = set1.intersection(set2)
unique_to_df1 = set1 - set2
unique_to_df2 = set2 - set1

# Print the results
print(f"Number of common protein changes: {len(common)}")
print(f"Number of unique protein changes in clinvar_result.xlsx: {len(unique_to_df1)}")
print(f"Number of unique protein changes in gnomAD.xlsx: {len(unique_to_df2)}")

Number of common protein changes: 51
Number of unique protein changes in clinvar_result.xlsx: 69
Number of unique protein changes in gnomAD.xlsx: 215

# 2 gnomAD

## 2.1 csv to excel

In [80]:
import pandas as pd

# Load the CSV file
csv_file = "00_data/gnomAD.csv"
df_gnomad = pd.read_csv(csv_file)

# Save as an Excel file
excel_file = "00_data/gnomAD.xlsx"
df_gnomad.to_excel(excel_file, index=False, engine='openpyxl')

print(f"CSV file converted to Excel: {excel_file}")

CSV file converted to Excel: 00_data/gnomAD.xlsx

## 2.2 view gnomAD data

In [81]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_gnomad = pd.read_excel('00_data/gnomAD.xlsx')

# Display the dataset in IPython style
display(df_gnomad)

,gnomAD ID,Chromosome,Position,rsIDs,Reference,Alternate,Source,Filters - exomes,Filters - genomes,Transcript,...,Homozygote Count Amish,Hemizygote Count Amish,Allele Count South Asian,Allele Number South Asian,Homozygote Count South Asian,Hemizygote Count South Asian,Allele Count Remaining,Allele Number Remaining,Homozygote Count Remaining,Hemizygote Count Remaining
0,X-18507022-C-A,X,18507022,NaN,C,A,gnomAD Exomes,AC0,NaN,ENST00000623535.2,...,0,0,0,47228,0,0,0,32581,0,0
1,X-18507025-A-T,X,18507025,NaN,A,T,gnomAD Exomes,AC0,NaN,ENST00000623535.2,...,0,0,0,48182,0,0,0,33314,0,0
2,X-18507026-C-T,X,18507026,NaN,C,T,gnomAD Exomes,AS_VQSR,NaN,ENST00000623535.2,...,0,0,1,48511,0,1,0,33958,0,0
3,X-18507028-G-A,X,18507028,NaN,G,A,gnomAD Exomes,PASS,NaN,ENST00000623535.2,...,0,0,0,48917,0,0,1,34634,0,0
4,X-18507029-C-A,X,18507029,NaN,C,A,gnomAD Exomes,AC0,NaN,ENST00000623535.2,...,0,0,0,49033,0,0,0,34927,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4603,X-18653612-C-T,X,18653612,rs1602318427,C,T,gnomAD Exomes,AC0,NaN,ENST00000379989.6,...,0,0,0,53064,0,0,0,45106,0,0
4604,X-18653614-A-C,X,18653614,NaN,A,C,gnomAD Exomes,PASS,NaN,ENST00000379989.6,...,0,0,0,52930,0,0,0,44818,0,0
4605,X-18653614-A-G,X,18653614,rs1244414729,A,G,"gnomAD Exomes,gnomAD Genomes",PASS,PASS,ENST00000379989.6,...,0,0,0,52802,0,0,1,44775,0,0
4606,X-18653615-T-C,X,18653615,NaN,T,C,gnomAD Exomes,PASS,NaN,ENST00000379989.6,...,0,0,1,52926,0,0,0,44862,0,0
4607,X-18653616-G-T,X,18653616,NaN,G,T,gnomAD Exomes,"AC0,AS_VQSR",NaN,ENST00000379989.6,...,0,0,0,52811,0,0,0,44847,0,0

In [83]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_gnomad = pd.read_excel('00_data/gnomAD.xlsx', sheet_name='Sheet1')

# Convert column names to DataFrame for better visualization
column_names_df = pd.DataFrame(df_gnomad.columns, columns=['Column Names'])

# Display the column names as a table
display(column_names_df)

                    Column Names
0                      gnomAD ID
1                     Chromosome
2                       Position
3                          rsIDs
4                      Reference
..                           ...
67  Hemizygote Count South Asian
68        Allele Count Remaining
69       Allele Number Remaining
70    Homozygote Count Remaining
71    Hemizygote Count Remaining

[72 rows x 1 columns]

## Value count gnomAD sheet1

In [31]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_gnomad = pd.read_excel('00_data/gnomAD.xlsx', sheet_name='Sheet1')

# Define columns to count
columns_to_count = ['VEP Annotation', 'ClinVar Germline Classification']

# Function to display value counts with total entries including NaNs
def show_value_counts_with_total(df, sheet_name, columns):
    print(f"\nValue counts for '{sheet_name}' sheet:")
    for col in columns:
        counts = df[col].value_counts(dropna=False).reset_index()
        counts.columns = [col, 'Count']
        display(counts)
        total = len(df[col])
        print(f"Total entries in '{col}': {total}\n")

# Show value counts for 'Sheet1' with totals
show_value_counts_with_total(df_gnomad, 'Sheet1', columns_to_count)

Value counts for 'Sheet1' sheet:

             VEP Annotation  Count
0            intron_variant   2563
1          missense_variant    971
2        synonymous_variant    483
3       3_prime_UTR_variant    235
4     splice_region_variant    146
5       5_prime_UTR_variant     67
6        frameshift_variant     37
7               stop_gained     32
8      splice_donor_variant     28
9   splice_acceptor_variant     21
10         inframe_deletion     12
11        inframe_insertion      7
12                stop_lost      4
13               start_lost      1
14    stop_retained_variant      1

Total entries in 'VEP Annotation': 4608

                ClinVar Germline Classification  Count
0                                           NaN   3994
1                                 Likely benign    266
2                        Uncertain significance    161
3                                        Benign     70
4                          Benign/Likely benign     39
5  Conflicting classifications of pathogenicity     35
6                                    Pathogenic     25
7                             Likely pathogenic     11
8                  Pathogenic/Likely pathogenic      7

Total entries in 'ClinVar Germline Classification': 4608

## 2.3 Missense_Variant

In [88]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel file
file_path = '00_data/gnomAD.xlsx'
df_gnomad = pd.read_excel(file_path, sheet_name='Sheet1')

# Filter for 'missense_variant' entries
missense_df = df_gnomad[df_gnomad['VEP Annotation'].str.contains('missense_variant', na=False)]

# Save the filtered data to a new sheet with an appropriate name
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl') as writer:
    missense_df.to_excel(writer, sheet_name='Missense_Variant', index=False)

print("Filtered data saved as 'Missense_Variant' in the same Excel file.")

Filtered data saved as 'Missense_Variant' in the same Excel file.

In [32]:
import pandas as pd
from IPython.display import display

# Load the Excel file
df_gnomad = pd.read_excel('00_data/gnomAD.xlsx', sheet_name='Missense_Variant')

# Define columns to count
columns_to_count = ['VEP Annotation', 'ClinVar Germline Classification']

# Function to display value counts with total entries including NaNs
def show_value_counts_with_total(df, sheet_name, columns):
    print(f"\nValue counts for '{sheet_name}' sheet:")
    for col in columns:
        counts = df[col].value_counts(dropna=False).reset_index()
        counts.columns = [col, 'Count']
        display(counts)
        total = len(df[col])
        print(f"Total entries in '{col}': {total}\n")

# Show value counts for 'Sheet1' with totals
show_value_counts_with_total(df_gnomad, 'Sheet1', columns_to_count)

Value counts for 'Sheet1' sheet:

     VEP Annotation  Count
0  missense_variant    971

Total entries in 'VEP Annotation': 971

                ClinVar Germline Classification  Count
0                                           NaN    705
1                        Uncertain significance    138
2                                 Likely benign     56
3  Conflicting classifications of pathogenicity     24
4                                        Benign     21
5                          Benign/Likely benign     12
6                             Likely pathogenic      7
7                                    Pathogenic      6
8                  Pathogenic/Likely pathogenic      2

Total entries in 'ClinVar Germline Classification': 971

## 2.4 Protein_change_converted: p.Lys2Arg to K2R

In [21]:
import pandas as pd
from openpyxl import load_workbook

# Full mapping of three-letter amino acid codes to one-letter codes
aa_mapping = {
    "Ala": "A", "Arg": "R", "Asn": "N", "Asp": "D",
    "Cys": "C", "Glu": "E", "Gln": "Q", "Gly": "G",
    "His": "H", "Ile": "I", "Leu": "L", "Lys": "K",
    "Met": "M", "Phe": "F", "Pro": "P", "Ser": "S",
    "Thr": "T", "Trp": "W", "Tyr": "Y", "Val": "V",
    "Sec": "U", "Pyl": "O", "Ter": "*"
}

# Load the Excel file and the specified sheet
file_path = '00_data/gnomAD.xlsx'
df_gnomad = pd.read_excel(file_path, sheet_name='Protein_Change_Converted')

# Strip 'p.' and store in a new column for parsing
df_gnomad['Protein Consequence (Three-Letter)'] = df_gnomad['Protein Consequence'].str.replace("p.", "", regex=False)

# Function to convert three-letter amino acid change to one-letter format
def convert_to_one_letter(protein_consequence):
    try:
        wt = protein_consequence[:3]                         # Wild-type (3-letter)
        mut = protein_consequence[-3:]                       # Mutant (3-letter)
        pos = protein_consequence[3:-3]                      # Position
        
        wt_1 = aa_mapping.get(wt, '?')
        mut_1 = aa_mapping.get(mut, '?')

        return f"{wt_1}{pos}{mut_1}"
    except Exception:
        return None

# Apply the function to create the corrected column
df_gnomad['Protein change (One-Letter)'] = df_gnomad['Protein Consequence (Three-Letter)'].apply(convert_to_one_letter)

# Save changes back to the same sheet (overwriting it)
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df_gnomad.to_excel(writer, sheet_name='Protein_Change_Converted', index=False)

print("Protein changes converted to one-letter format and saved in existing sheet 'Protein_Change_Converted'.")

Protein changes converted to one-letter format and saved in existing sheet 'Protein_Change_Converted'.

### Sanity check one letter code

In [23]:
import pandas as pd
import re

# Load the updated sheet
file_path = '00_data/gnomAD.xlsx'
df = pd.read_excel(file_path, sheet_name='Protein_Change_Converted')

# Define set of valid one-letter amino acid codes (including stop codon '*')
valid_aa = set('ACDEFGHIKLMNPQRSTVWY*')

# Sanity check function
def is_valid_change(change):
    if not isinstance(change, str):
        return False
    match = re.match(r'^([A-Z*])(\d+)([A-Z*])$', change)
    if match:
        wt, pos, mut = match.groups()
        return wt in valid_aa and mut in valid_aa
    return False

# Apply sanity check
df['Is_Valid_One_Letter_Change'] = df['Protein change (One-Letter)'].apply(is_valid_change)

# Report results
valid_count = df['Is_Valid_One_Letter_Change'].sum()
invalid_count = (~df['Is_Valid_One_Letter_Change']).sum()

print(f"\n✅ Valid entries: {valid_count}")
print(f"❌ Invalid entries: {invalid_count}")

# Show examples of invalid entries
if invalid_count > 0:
    print("\nExamples of invalid entries:")
    print(df.loc[~df['Is_Valid_One_Letter_Change'], ['Protein Consequence', 'Protein change (One-Letter)']].head())

✅ Valid entries: 971
❌ Invalid entries: 0

In [24]:
import pandas as pd
from IPython.display import display

# Load the updated Excel file
df_gnomad = pd.read_excel('00_data/gnomAD.xlsx', sheet_name='Protein_Change_Converted')

# Display the dataset in a clean format
display(df_gnomad)

,gnomAD ID,Chromosome,Position,rsIDs,Reference,Alternate,Source,Filters - exomes,Filters - genomes,Transcript,...,Allele Count South Asian,Allele Number South Asian,Homozygote Count South Asian,Hemizygote Count South Asian,Allele Count Remaining,Allele Number Remaining,Homozygote Count Remaining,Hemizygote Count Remaining,Protein Consequence (Three-Letter),Protein change (One-Letter)
0,X-18507101-A-G,X,18507101,NaN,A,G,gnomAD Exomes,AC0,NaN,ENST00000623535.2,...,0,56517,0,0,0,47048,0,0,Lys2Arg,K2R
1,X-18507103-A-T,X,18507103,rs138539908,A,T,"gnomAD Exomes,gnomAD Genomes",PASS,PASS,ENST00000623535.2,...,0,56357,0,0,0,47093,0,0,Ile3Phe,I3F
2,X-18507107-C-T,X,18507107,NaN,C,T,gnomAD Exomes,PASS,NaN,ENST00000623535.2,...,0,56593,0,0,1,47210,0,1,Pro4Leu,P4L
3,X-18507109-A-G,X,18507109,rs767844474,A,G,"gnomAD Exomes,gnomAD Genomes",PASS,PASS,ENST00000623535.2,...,0,56443,0,0,1,47190,0,0,Asn5Asp,N5D
4,X-18507113-T-C,X,18507113,rs746036179,T,C,gnomAD Exomes,PASS,NaN,ENST00000623535.2,...,6,56668,0,3,0,47290,0,0,Ile6Thr,I6T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,X-18653536-G-A,X,18653536,rs201765217,G,A,"gnomAD Exomes,gnomAD Genomes",PASS,PASS,ENST00000379989.6,...,0,56824,0,0,1,47593,0,1,Gly1029Ser,G1029S
967,X-18653536-G-C,X,18653536,NaN,G,C,gnomAD Exomes,AS_VQSR,NaN,ENST00000379989.6,...,0,56952,0,0,0,47638,0,0,Gly1029Arg,G1029R
968,X-18653537-G-T,X,18653537,rs1250531842,G,T,gnomAD Exomes,PASS,NaN,ENST00000379989.6,...,0,56932,0,0,0,47638,0,0,Gly1029Val,G1029V
969,X-18653539-A-G,X,18653539,NaN,A,G,gnomAD Exomes,PASS,NaN,ENST00000379989.6,...,0,56959,0,0,0,47634,0,0,Lys1030Glu,K1030E
970,X-18653540-A-T,X,18653540,NaN,A,T,gnomAD Exomes,PASS,NaN,ENST00000379989.6,...,0,56928,0,0,0,47628,0,0,Lys1030Met,K1030M

In [25]:
import pandas as pd

# Load the updated Excel file
file_path = '00_data/gnomAD.xlsx'
df_protein_change = pd.read_excel(file_path, sheet_name='Protein_Change_Converted')

# Print column names
print("\nColumn Names in 'Protein_Change_Converted' sheet:")
print(df_protein_change.columns)

Column Names in 'Protein_Change_Converted' sheet:
Index(['gnomAD ID', 'Chromosome', 'Position', 'rsIDs', 'Reference',
       'Alternate', 'Source', 'Filters - exomes', 'Filters - genomes',
       'Transcript', 'HGVS Consequence', 'Protein Consequence',
       'Transcript Consequence', 'VEP Annotation',
       'ClinVar Germline Classification', 'ClinVar Variation ID', 'Flags',
       'Allele Count', 'Allele Number', 'Allele Frequency', 'Homozygote Count',
       'Hemizygote Count', 'Filters - joint', 'GroupMax FAF group',
       'GroupMax FAF frequency', 'cadd', 'revel_max', 'spliceai_ds_max',
       'pangolin_largest_ds', 'phylop', 'sift_max', 'polyphen_max',
       'Allele Count African/African American',
       'Allele Number African/African American',
       'Homozygote Count African/African American',
       'Hemizygote Count African/African American',
       'Allele Count Admixed American', 'Allele Number Admixed American',
       'Homozygote Count Admixed American',
       'Hemizygote Count Admixed American', 'Allele Count Ashkenazi Jewish',
       'Allele Number Ashkenazi Jewish', 'Homozygote Count Ashkenazi Jewish',
       'Hemizygote Count Ashkenazi Jewish', 'Allele Count East Asian',
       'Allele Number East Asian', 'Homozygote Count East Asian',
       'Hemizygote Count East Asian', 'Allele Count European (Finnish)',
       'Allele Number European (Finnish)',
       'Homozygote Count European (Finnish)',
       'Hemizygote Count European (Finnish)', 'Allele Count Middle Eastern',
       'Allele Number Middle Eastern', 'Homozygote Count Middle Eastern',
       'Hemizygote Count Middle Eastern',
       'Allele Count European (non-Finnish)',
       'Allele Number European (non-Finnish)',
       'Homozygote Count European (non-Finnish)',
       'Hemizygote Count European (non-Finnish)', 'Allele Count Amish',
       'Allele Number Amish', 'Homozygote Count Amish',
       'Hemizygote Count Amish', 'Allele Count South Asian',
       'Allele Number South Asian', 'Homozygote Count South Asian',
       'Hemizygote Count South Asian', 'Allele Count Remaining',
       'Allele Number Remaining', 'Homozygote Count Remaining',
       'Hemizygote Count Remaining', 'Protein Consequence (Three-Letter)',
       'Protein change (One-Letter)'],
      dtype='object')

In [16]:
import pandas as pd

# Load the Excel sheet
file_path = '00_data/gnomAD.xlsx'
df_protein_change = pd.read_excel(file_path, sheet_name='Protein_Change_Converted')

# Print column names (optional for verification)
print("\nColumn Names in 'Protein_Change_Converted' sheet:")
print(df_protein_change.columns)

# Value counts for 'VEP Annotation'
print("\nValue Counts for 'VEP Annotation':")
print(df_protein_change['VEP Annotation'].value_counts(dropna=False))

# Value counts for 'ClinVar Germline Classification'
print("\nValue Counts for 'ClinVar Germline Classification':")
print(df_protein_change['ClinVar Germline Classification'].value_counts(dropna=False))

Column Names in 'Protein_Change_Converted' sheet:
Index(['gnomAD ID', 'Chromosome', 'Position', 'rsIDs', 'Reference',
       'Alternate', 'Source', 'Filters - exomes', 'Filters - genomes',
       'Transcript', 'HGVS Consequence', 'Protein Consequence',
       'Transcript Consequence', 'VEP Annotation',
       'ClinVar Germline Classification', 'ClinVar Variation ID', 'Flags',
       'Allele Count', 'Allele Number', 'Allele Frequency', 'Homozygote Count',
       'Hemizygote Count', 'Filters - joint', 'GroupMax FAF group',
       'GroupMax FAF frequency', 'cadd', 'revel_max', 'spliceai_ds_max',
       'pangolin_largest_ds', 'phylop', 'sift_max', 'polyphen_max',
       'Allele Count African/African American',
       'Allele Number African/African American',
       'Homozygote Count African/African American',
       'Hemizygote Count African/African American',
       'Allele Count Admixed American', 'Allele Number Admixed American',
       'Homozygote Count Admixed American',
       'Hemizygote Count Admixed American', 'Allele Count Ashkenazi Jewish',
       'Allele Number Ashkenazi Jewish', 'Homozygote Count Ashkenazi Jewish',
       'Hemizygote Count Ashkenazi Jewish', 'Allele Count East Asian',
       'Allele Number East Asian', 'Homozygote Count East Asian',
       'Hemizygote Count East Asian', 'Allele Count European (Finnish)',
       'Allele Number European (Finnish)',
       'Homozygote Count European (Finnish)',
       'Hemizygote Count European (Finnish)', 'Allele Count Middle Eastern',
       'Allele Number Middle Eastern', 'Homozygote Count Middle Eastern',
       'Hemizygote Count Middle Eastern',
       'Allele Count European (non-Finnish)',
       'Allele Number European (non-Finnish)',
       'Homozygote Count European (non-Finnish)',
       'Hemizygote Count European (non-Finnish)', 'Allele Count Amish',
       'Allele Number Amish', 'Homozygote Count Amish',
       'Hemizygote Count Amish', 'Allele Count South Asian',
       'Allele Number South Asian', 'Homozygote Count South Asian',
       'Hemizygote Count South Asian', 'Allele Count Remaining',
       'Allele Number Remaining', 'Homozygote Count Remaining',
       'Hemizygote Count Remaining', 'Protein Consequence (Three-Letter)',
       'Protein change (One-Letter)'],
      dtype='object')

Value Counts for 'VEP Annotation':
VEP Annotation
missense_variant    971
Name: count, dtype: int64

Value Counts for 'ClinVar Germline Classification':
ClinVar Germline Classification
NaN                                             705
Uncertain significance                          138
Likely benign                                    56
Conflicting classifications of pathogenicity     24
Benign                                           21
Benign/Likely benign                             12
Likely pathogenic                                 7
Pathogenic                                        6
Pathogenic/Likely pathogenic                      2
Name: count, dtype: int64

## 2.5 make 'mutation' column with 'wild' 'position' 'mutant'

## 2.5 New sheet 'NaN' discarded on 'ClinVar Germline Classification'

In [26]:
import pandas as pd

# Load the Excel file and the specific sheet
file_path = '00_data/gnomAD.xlsx'
df = pd.read_excel(file_path, sheet_name='Protein_Change_Converted')

# Filter out rows where 'ClinVar Germline Classification' is not NaN
df_filtered = df[df['ClinVar Germline Classification'].notna()]

# Save to a new sheet in the same Excel file
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df_filtered.to_excel(writer, sheet_name='ClinVar_Classified_Only', index=False)

print("Filtered data saved to new sheet 'ClinVar_Classified_Only' in gnomAD.xlsx.")

Filtered data saved to new sheet 'ClinVar_Classified_Only' in gnomAD.xlsx.

In [29]:
import pandas as pd

# Load the new sheet
file_path = '00_data/gnomAD.xlsx'
df_filtered = pd.read_excel(file_path, sheet_name='ClinVar_Classified_Only')

# Function to get value counts with total count
def value_counts_with_total(df, column_name):
    counts = df[column_name].value_counts(dropna=False)
    total = len(df[column_name])
    print(counts)
    print(f"\nTotal entries in '{column_name}': {total}")

# Display the first few rows (optional)
print("\nPreview of 'ClinVar_Classified_Only' sheet:")
print(df_filtered.head())

# Use the function for 'ClinVar Germline Classification'
print("\nValue Counts for 'ClinVar Germline Classification':")
value_counts_with_total(df_filtered, 'ClinVar Germline Classification')

Preview of 'ClinVar_Classified_Only' sheet:
        gnomAD ID Chromosome  Position         rsIDs Reference Alternate  \
0  X-18507103-A-T          X  18507103   rs138539908         A         T
1  X-18507109-A-G          X  18507109   rs767844474         A         G
2  X-18507113-T-C          X  18507113   rs746036179         T         C
3  X-18507122-T-C          X  18507122  rs1569197962         T         C
4  X-18507154-G-A          X  18507154   rs267608418         G         A

                         Source Filters - exomes Filters - genomes  \
0  gnomAD Exomes,gnomAD Genomes             PASS              PASS
1  gnomAD Exomes,gnomAD Genomes             PASS              PASS
2                 gnomAD Exomes             PASS               NaN
3                 gnomAD Exomes             PASS               NaN
4                 gnomAD Exomes      AC0,AS_VQSR               NaN

          Transcript  ... Allele Count South Asian Allele Number South Asian  \
0  ENST00000623535.2  ...                        0                     56357
1  ENST00000623535.2  ...                        0                     56443
2  ENST00000623535.2  ...                        6                     56668
3  ENST00000623535.2  ...                        0                     56785
4  ENST00000623535.2  ...                        0                     56426

  Homozygote Count South Asian Hemizygote Count South Asian  \
0                            0                            0
1                            0                            0
2                            0                            3
3                            0                            0
4                            0                            0

  Allele Count Remaining  Allele Number Remaining  Homozygote Count Remaining  \
0                      0                    47093                           0
1                      1                    47190                           0
2                      0                    47290                           0
3                      0                    47403                           0
4                      0                    46927                           0

   Hemizygote Count Remaining  Protein Consequence (Three-Letter)  \
0                           0                             Ile3Phe
1                           0                             Asn5Asp
2                           0                             Ile6Thr
3                           0                             Val9Ala
4                           0                            Gly20Ser

   Protein change (One-Letter)
0                          I3F
1                          N5D
2                          I6T
3                          V9A
4                         G20S

[5 rows x 74 columns]

Value Counts for 'ClinVar Germline Classification':
ClinVar Germline Classification
Uncertain significance                          138
Likely benign                                    56
Conflicting classifications of pathogenicity     24
Benign                                           21
Benign/Likely benign                             12
Likely pathogenic                                 7
Pathogenic                                        6
Pathogenic/Likely pathogenic                      2
Name: count, dtype: int64

Total entries in 'ClinVar Germline Classification': 266

## 3 Comparison: ClinVar vs gnomAD

In [34]:
import pandas as pd

# Load datasets from Excel files
df_clinvar = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_missense_only')
df_gnomad = pd.read_excel('00_data/gnomAD.xlsx', sheet_name='Protein_Change_Converted')

# Extract relevant columns and clean (drop NaN, convert to string)
set_clinvar = set(df_clinvar['Protein change'].dropna().astype(str))
set_gnomad = set(df_gnomad['Protein change (One-Letter)'].dropna().astype(str))

# Calculate common and unique protein changes
common = set_clinvar.intersection(set_gnomad)
unique_clinvar = set_clinvar - set_gnomad
unique_gnomad = set_gnomad - set_clinvar

# Print results with ClinVar first
print(f"Number of common entries: {len(common)}")
print(f"Number of unique entries in ClinVar: {len(unique_clinvar)}")
print(f"Number of unique entries in gnomAD: {len(unique_gnomad)}")

Number of common entries: 51
Number of unique entries in ClinVar: 69
Number of unique entries in gnomAD: 913

In [42]:
import pandas as pd

def print_comparison_info(file1, sheet1, col1, file2, sheet2, col2):
    """Prints the details of what is being compared."""
    print("=== Dataset Comparison Information ===")
    print(f"ClinVar File           : {file1}")
    print(f"ClinVar Sheet          : {sheet1}")
    print(f"ClinVar Column         : {col1}")
    print(f"gnomAD File            : {file2}")
    print(f"gnomAD Sheet           : {sheet2}")
    print(f"gnomAD Column          : {col2}")
    print("======================================\n")

# File, sheet, and column metadata
clinvar_file = '00_data/clinvar_result.xlsx'
clinvar_sheet = 'CDKL5_missense_only'
clinvar_column = 'Protein change'

gnomad_file = '00_data/gnomAD.xlsx'
gnomad_sheet = 'Protein_Change_Converted'
gnomad_column = 'Protein change (One-Letter)'

# Print comparison info
print_comparison_info(clinvar_file, clinvar_sheet, clinvar_column, gnomad_file, gnomad_sheet, gnomad_column)

# Load datasets
df_clinvar = pd.read_excel(clinvar_file, sheet_name=clinvar_sheet)
df_gnomad = pd.read_excel(gnomad_file, sheet_name=gnomad_sheet)

# Extract sets of protein changes
set_clinvar = set(df_clinvar[clinvar_column].dropna().astype(str))
set_gnomad = set(df_gnomad[gnomad_column].dropna().astype(str))

# Compare sets
common = set_clinvar.intersection(set_gnomad)
unique_clinvar = set_clinvar - set_gnomad
unique_gnomad = set_gnomad - set_clinvar

# Print basic stats
print(f"Number of common entries: {len(common)}")
print(f"Number of unique entries in ClinVar: {len(unique_clinvar)}")
print(f"Number of unique entries in gnomAD (set difference): {len(unique_gnomad)}")

# Filter gnomAD for unique entries
unique_gnomad_df = df_gnomad[df_gnomad[gnomad_column].isin(unique_gnomad)]

# Check duplicates
duplicates = unique_gnomad_df.duplicated(subset=[gnomad_column]).sum()
print(f"Number of duplicate entries in unique gnomAD dataset: {duplicates}")

# Drop duplicates
unique_gnomad_df = unique_gnomad_df.drop_duplicates(subset=[gnomad_column])

# Final consistency check
if len(unique_gnomad_df) == len(unique_gnomad):
    print("No extra entries found. Sets and dataframe filtering consistent.")
else:
    print("⚠️ Inconsistency found: check for repeated rows.")

# Classification value counts
classification_counts = unique_gnomad_df['ClinVar Germline Classification'].value_counts(dropna=False)
print("\nValue counts of 'ClinVar Germline Classification' for unique gnomAD entries:")
print(classification_counts)

# Total entries
print(f"\nTotal unique gnomAD entries counted: {classification_counts.sum()}")

=== Dataset Comparison Information ===
ClinVar File           : 00_data/clinvar_result.xlsx
ClinVar Sheet          : CDKL5_missense_only
ClinVar Column         : Protein change
gnomAD File            : 00_data/gnomAD.xlsx
gnomAD Sheet           : Protein_Change_Converted
gnomAD Column          : Protein change (One-Letter)
======================================

Number of common entries: 51
Number of unique entries in ClinVar: 69
Number of unique entries in gnomAD (set difference): 913
Number of duplicate entries in unique gnomAD dataset: 7
No extra entries found. Sets and dataframe filtering consistent.

Value counts of 'ClinVar Germline Classification' for unique gnomAD entries:
ClinVar Germline Classification
NaN                                             699
Uncertain significance                          125
Likely benign                                    46
Conflicting classifications of pathogenicity     20
Benign/Likely benign                              9
Benign                                            8
Likely pathogenic                                 3
Pathogenic                                        3
Name: count, dtype: int64

Total unique gnomAD entries counted: 913

# 4 just last one: how many AF pulled in previous clinvar

In [43]:
!ls 00_data/

clinvar_result_copy.xlsx  clinvar_result.xlsx  gnomAD.xlsx
clinvar_result.txt	  gnomAD.csv	       protein_change_comparison.xlsx

In [44]:
import pandas as pd

# Load the Excel file and list sheet names
file_path = '00_data/clinvar_result_copy.xlsx'
xls = pd.ExcelFile(file_path)

# Print all sheet names
print("Sheet names in the Excel file:")
print(xls.sheet_names)

Sheet names in the Excel file:
['Sheet1', 'CDKL5_rows', 'CDKL5_missense', 'CDKL5_missense_only', 'CDKL5_missense_AF']

In [45]:
import pandas as pd

# Define the file path and sheet name
file_path = '00_data/clinvar_result_copy.xlsx'
sheet_name = 'CDKL5_missense_AF'

# Load the sheet
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Show the column names
print("Columns in the 'CDKL5_missense_AF' sheet:")
print(df.columns.tolist())

Columns in the 'CDKL5_missense_AF' sheet:
['Name', 'Gene(s)', 'Protein change', 'gnomAD_AF', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24']

In [46]:
import pandas as pd

# Load the sheet
df = pd.read_excel('00_data/clinvar_result_copy.xlsx', sheet_name='CDKL5_missense_AF')

# Count non-empty and empty values in 'gnomAD_AF' column
non_empty_count = df['gnomAD_AF'].notna().sum()
empty_count = df['gnomAD_AF'].isna().sum()

# Print the results
print(f"Number of entries with a value in 'gnomAD_AF': {non_empty_count}")
print(f"Number of empty (NaN) entries in 'gnomAD_AF': {empty_count}")

Number of entries with a value in 'gnomAD_AF': 48
Number of empty (NaN) entries in 'gnomAD_AF': 72

# =============================== #

# 5 The 1000 Genomes

## 5.1 1KGP cdkl5 grch38 data

In [26]:
import pandas as pd
from IPython.display import display

# Load the dataset
file_path = '00_data/1kgp_cdkl5_grch38.xlsx'
df_1kgp = pd.read_excel(file_path, sheet_name='Sheet1')

# Display the entire dataset
display(df_1kgp)

,CHROM,POS,REF,ALT,RefGenome,AF,Gene,Consequence,HGVSc,HGVSp
0,chrX,18425583,G,C,GRCh38,0.000265,CDKL5,5_prime_UTR_variant,ENST00000379996.7:c.-275G>C,NaN
1,chrX,18425593,C,G,GRCh38,0.000530,CDKL5,5_prime_UTR_variant,ENST00000379996.7:c.-265C>G,NaN
2,chrX,18425637,C,G,GRCh38,0.002384,CDKL5,5_prime_UTR_variant,ENST00000379996.7:c.-221C>G,NaN
3,chrX,18425667,C,T,GRCh38,0.000265,CDKL5,5_prime_UTR_variant,ENST00000379996.7:c.-191C>T,NaN
4,chrX,18425805,A,T,GRCh38,0.000265,CDKL5,intron_variant,ENST00000379996.7:c.-163+110A>T,NaN
...,...,...,...,...,...,...,...,...,...,...
4475,chrX,18653534,C,T,GRCh38,0.000265,RS1,intron_variant,ENST00000379984.4:c.184+3119G>A,NaN
4476,chrX,18653535,G,A,GRCh38,0.001324,RS1,intron_variant,ENST00000379984.4:c.184+3118C>T,NaN
4477,chrX,18653548,C,T,GRCh38,0.000265,RS1,intron_variant,ENST00000379984.4:c.184+3105G>A,NaN
4478,chrX,18653620,C,G,GRCh38,0.000795,RS1,intron_variant,ENST00000379984.4:c.184+3033G>C,NaN
4479,chrX,18653623,C,T,GRCh38,0.000265,RS1,intron_variant,ENST00000379984.4:c.184+3030G>A,NaN

## 5.2 columns in Sheet1

In [27]:
import pandas as pd

# Load the dataset
file_path = '00_data/1kgp_cdkl5_grch38.xlsx'
df_1kgp = pd.read_excel(file_path, sheet_name='Sheet1')

# View column names
print("Columns in Sheet1:")
print(df_1kgp.columns.tolist())

Columns in Sheet1:
['CHROM', 'POS', 'REF', 'ALT', 'RefGenome', 'AF', 'Gene', 'Consequence', 'HGVSc', 'HGVSp']

## 5.3 value counts 'Consequence'

In [28]:
import pandas as pd
from IPython.display import display

# Load the dataset
df_1kgp = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='Sheet1')

# Get value counts as a DataFrame
consequence_counts = df_1kgp['Consequence'].value_counts(dropna=False).rename_axis('Consequence').reset_index(name='Count')

# Display the table
print("Value counts for 'Consequence':")
display(consequence_counts)

# Print total count
print(f"\nTotal number of entries in 'Consequence': {consequence_counts['Count'].sum()}")

Value counts for 'Consequence':

                                          Consequence  Count
0                                      intron_variant   4163
1                               upstream_gene_variant    114
2                             downstream_gene_variant     86
3                                 3_prime_UTR_variant     56
4                                  synonymous_variant     27
5                                    missense_variant     19
6                                 5_prime_UTR_variant      8
7   splice_polypyrimidine_tract_variant&intron_var...      4
8           splice_region_variant&5_prime_UTR_variant      1
9                splice_region_variant&intron_variant      1
10       splice_donor_5th_base_variant&intron_variant      1

Total number of entries in 'Consequence': 4480

## 5.4 pull out 'missense_variant' from 'Consequence' column of 'Sheet1'

In [29]:
import pandas as pd

# Define file path
file_path = '00_data/1kgp_cdkl5_grch38.xlsx'

# Load original Excel file
with pd.ExcelFile(file_path) as xls:
    df_all = xls.parse('Sheet1')  # Load Sheet1

# Filter for missense_variant rows
missense_df = df_all[df_all['Consequence'] == 'missense_variant']

# Save to a new sheet in the same Excel file
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    missense_df.to_excel(writer, sheet_name='missense_only', index=False)

print(f"Saved {len(missense_df)} 'missense_variant' entries to sheet 'missense_only' in {file_path}")

Saved 19 'missense_variant' entries to sheet 'missense_only' in 00_data/1kgp_cdkl5_grch38.xlsx

## 5.5 view the new sheet

In [30]:
import pandas as pd
from IPython.display import display

# Load the new sheet 'missense_only' from the Excel file
df_missense = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_only')

# Display the dataframe in a nice table format
display(df_missense)

,CHROM,POS,REF,ALT,RefGenome,AF,Gene,Consequence,HGVSc,HGVSp
0,chrX,18507103,A,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.7A>T,ENSP00000369325.3:p.Ile3Phe
1,chrX,18507109,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.13A>G,ENSP00000369325.3:p.Asn5Asp
2,chrX,18575447,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.239G>A,ENSP00000369325.3:p.Arg80His
3,chrX,18588118,G,C,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.719G>C,ENSP00000369325.3:p.Ser240Thr
4,chrX,18603988,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1064G>A,ENSP00000369325.3:p.Arg355Gln
5,chrX,18604012,A,G,GRCh38,0.000530,CDKL5,missense_variant,ENST00000379989.6:c.1088A>G,ENSP00000369325.3:p.Asn363Ser
6,chrX,18604366,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1442C>G,ENSP00000369325.3:p.Ser481Cys
7,chrX,18604686,C,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1762C>T,ENSP00000369325.3:p.Pro588Ser
8,chrX,18613214,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2215C>G,ENSP00000369325.3:p.Leu739Val
9,chrX,18613214,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2215C>G,ENSP00000369325.3:p.Leu739Val
10,chrX,18613242,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2243A>G,ENSP00000369325.3:p.Asn748Ser
11,chrX,18619962,A,C,GRCh38,0.016689,CDKL5,missense_variant,ENST00000379989.6:c.2372A>C,ENSP00000369325.3:p.Gln791Pro
12,chrX,18628543,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2669G>A,ENSP00000369325.3:p.Arg890Gln
13,chrX,18642131,G,A,GRCh38,0.000795,RS1,missense_variant,ENST00000379984.4:c.548C>T,ENSP00000369320.3:p.Thr183Ile
14,chrX,18644519,C,T,GRCh38,0.000530,RS1,missense_variant,ENST00000379984.4:c.433G>A,ENSP00000369320.3:p.Asp145Asn
15,chrX,18644580,C,A,GRCh38,0.000265,RS1,missense_variant,ENST00000379984.4:c.372G>T,ENSP00000369320.3:p.Gln124His
16,chrX,18647222,T,C,GRCh38,0.015099,RS1,missense_variant,ENST00000379984.4:c.295A>G,ENSP00000369320.3:p.Asn99Asp
17,chrX,18647284,G,A,GRCh38,0.000265,RS1,missense_variant,ENST00000379984.4:c.233C>T,ENSP00000369320.3:p.Pro78Leu
18,chrX,18647329,C,T,GRCh38,0.000265,RS1,missense_variant,ENST00000379984.4:c.188G>A,ENSP00000369320.3:p.Cys63Tyr

## 5.6 value count 'Gene'

In [31]:
import pandas as pd

# Load the 'missense_only' sheet
df_missense = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_only')

# Value counts for 'Gene' column
gene_counts = df_missense['Gene'].value_counts(dropna=False)

print("Value counts for 'Gene':")
print(gene_counts)

# Also print the total count (number of rows)
print(f"\nTotal number of entries: {len(df_missense)}")

Value counts for 'Gene':
Gene
CDKL5    13
RS1       6
Name: count, dtype: int64

Total number of entries: 19

## 5.7 pull out 'CDKL5' from 'Gene'

In [32]:
import pandas as pd

file_path = '00_data/1kgp_cdkl5_grch38.xlsx'

# Load Excel file
xls = pd.ExcelFile(file_path)

# Print sheet names
print("Sheets in the Excel file:")
for sheet in xls.sheet_names:
    print("-", sheet)

Sheets in the Excel file:
- Sheet1
- missense_only

In [33]:
import pandas as pd

# File path
file_path = '00_data/1kgp_cdkl5_grch38.xlsx'

# Load the missense sheet
df = pd.read_excel(file_path, sheet_name='missense_only')

# Filter for Gene == 'CDKL5'
df_cdkl5 = df[df['Gene'] == 'CDKL5']

# Save to the same Excel file, appending as new sheet 'CDKL5_only'
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df_cdkl5.to_excel(writer, sheet_name='missense_cdkl5_only', index=False)

In [34]:
import pandas as pd
from IPython.display import display

# Load the new sheet 'missense_only' from the Excel file
df_missense = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_cdkl5_only')

# Display the dataframe in a nice table format
display(df_missense)

,CHROM,POS,REF,ALT,RefGenome,AF,Gene,Consequence,HGVSc,HGVSp
0,chrX,18507103,A,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.7A>T,ENSP00000369325.3:p.Ile3Phe
1,chrX,18507109,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.13A>G,ENSP00000369325.3:p.Asn5Asp
2,chrX,18575447,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.239G>A,ENSP00000369325.3:p.Arg80His
3,chrX,18588118,G,C,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.719G>C,ENSP00000369325.3:p.Ser240Thr
4,chrX,18603988,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1064G>A,ENSP00000369325.3:p.Arg355Gln
5,chrX,18604012,A,G,GRCh38,0.000530,CDKL5,missense_variant,ENST00000379989.6:c.1088A>G,ENSP00000369325.3:p.Asn363Ser
6,chrX,18604366,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1442C>G,ENSP00000369325.3:p.Ser481Cys
7,chrX,18604686,C,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1762C>T,ENSP00000369325.3:p.Pro588Ser
8,chrX,18613214,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2215C>G,ENSP00000369325.3:p.Leu739Val
9,chrX,18613214,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2215C>G,ENSP00000369325.3:p.Leu739Val
10,chrX,18613242,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2243A>G,ENSP00000369325.3:p.Asn748Ser
11,chrX,18619962,A,C,GRCh38,0.016689,CDKL5,missense_variant,ENST00000379989.6:c.2372A>C,ENSP00000369325.3:p.Gln791Pro
12,chrX,18628543,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2669G>A,ENSP00000369325.3:p.Arg890Gln

## 5.8 Check for any duplicates

In [36]:
import pandas as pd

file_path = '00_data/1kgp_cdkl5_grch38.xlsx'

# Load the Excel file and the sheet with missense_variant data (assuming it's called 'missense_variant')
xls = pd.ExcelFile(file_path)
df = pd.read_excel(xls, sheet_name='missense_cdkl5_only')

# Check for duplicates based on all columns (or choose specific columns if preferred)
duplicates = df.duplicated()
num_duplicates = duplicates.sum()
print(f"Number of duplicate rows: {num_duplicates}")

# Remove duplicates
df_unique = df.drop_duplicates()

# Save the unique dataframe as a new sheet
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df_unique.to_excel(writer, sheet_name='missense_cdkl5_unique', index=False)

print("Saved unique entries in sheet 'missense_cdkl5_unique'.")

Number of duplicate rows: 1
Saved unique entries in sheet 'missense_cdkl5_unique'.

In [37]:
import pandas as pd
from IPython.display import display

# Load the new sheet 'missense_only' from the Excel file
df_missense = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_cdkl5_unique')

# Display the dataframe in a nice table format
display(df_missense)

,CHROM,POS,REF,ALT,RefGenome,AF,Gene,Consequence,HGVSc,HGVSp
0,chrX,18507103,A,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.7A>T,ENSP00000369325.3:p.Ile3Phe
1,chrX,18507109,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.13A>G,ENSP00000369325.3:p.Asn5Asp
2,chrX,18575447,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.239G>A,ENSP00000369325.3:p.Arg80His
3,chrX,18588118,G,C,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.719G>C,ENSP00000369325.3:p.Ser240Thr
4,chrX,18603988,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1064G>A,ENSP00000369325.3:p.Arg355Gln
5,chrX,18604012,A,G,GRCh38,0.000530,CDKL5,missense_variant,ENST00000379989.6:c.1088A>G,ENSP00000369325.3:p.Asn363Ser
6,chrX,18604366,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1442C>G,ENSP00000369325.3:p.Ser481Cys
7,chrX,18604686,C,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1762C>T,ENSP00000369325.3:p.Pro588Ser
8,chrX,18613214,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2215C>G,ENSP00000369325.3:p.Leu739Val
9,chrX,18613242,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2243A>G,ENSP00000369325.3:p.Asn748Ser
10,chrX,18619962,A,C,GRCh38,0.016689,CDKL5,missense_variant,ENST00000379989.6:c.2372A>C,ENSP00000369325.3:p.Gln791Pro
11,chrX,18628543,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2669G>A,ENSP00000369325.3:p.Arg890Gln

## 5.9 missense_cdkl5_unique_prot_change_1L

In [40]:
import pandas as pd

# File path and sheet names
file_path = '00_data/1kgp_cdkl5_grch38.xlsx'
input_sheet = 'missense_cdkl5_unique'
output_sheet = 'missense_cdkl5_unique_prot_chan'  # shortened sheet name, max 31 chars

# Load the Excel file and data
xls = pd.ExcelFile(file_path)
df = pd.read_excel(xls, sheet_name=input_sheet)

# Extract protein change info from 'HGVSp' column after ':p.'
df['Protein change 3L'] = df['HGVSp'].str.extract(r':p\.(.+)')

# Three-letter to one-letter AA code dictionary
aa_3to1 = {
    'Ala':'A', 'Arg':'R', 'Asn':'N', 'Asp':'D', 'Cys':'C',
    'Glu':'E', 'Gln':'Q', 'Gly':'G', 'His':'H', 'Ile':'I',
    'Leu':'L', 'Lys':'K', 'Met':'M', 'Phe':'F', 'Pro':'P',
    'Ser':'S', 'Thr':'T', 'Trp':'W', 'Tyr':'Y', 'Val':'V',
    'Sec':'U', 'Pyl':'O', 'Asx':'B', 'Glx':'Z', 'Xaa':'X'
}

# Function to convert 3-letter code protein change to 1-letter code
import re
def convert_3to1(prot_change_3L):
    if pd.isna(prot_change_3L):
        return prot_change_3L
    # Regex pattern to extract: wildtype (3 letters), position (number), mutant (3 letters)
    m = re.match(r'([A-Z][a-z]{2})(\d+)([A-Z][a-z]{2})', prot_change_3L)
    if not m:
        return prot_change_3L  # return as-is if pattern doesn't match
    wt_3, pos, mut_3 = m.groups()
    wt_1 = aa_3to1.get(wt_3, wt_3)
    mut_1 = aa_3to1.get(mut_3, mut_3)
    return f"{wt_1}{pos}{mut_1}"

# Apply conversion and add new column
df['Protein change'] = df['Protein change 3L'].apply(convert_3to1)

# Save to the same Excel file, replacing the output sheet if it exists
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df.to_excel(writer, sheet_name=output_sheet, index=False)

print(f"Saved updated dataframe with protein change columns to sheet '{output_sheet}'.")

Saved updated dataframe with protein change columns to sheet 'missense_cdkl5_unique_prot_chan'.

In [41]:
import pandas as pd
from IPython.display import display

# Load the new sheet 'missense_only' from the Excel file
df_missense = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_cdkl5_unique_prot_chan')

# Display the dataframe in a nice table format
display(df_missense)

,CHROM,POS,REF,ALT,RefGenome,AF,Gene,Consequence,HGVSc,HGVSp,Protein change 3L,Protein change
0,chrX,18507103,A,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.7A>T,ENSP00000369325.3:p.Ile3Phe,Ile3Phe,I3F
1,chrX,18507109,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.13A>G,ENSP00000369325.3:p.Asn5Asp,Asn5Asp,N5D
2,chrX,18575447,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.239G>A,ENSP00000369325.3:p.Arg80His,Arg80His,R80H
3,chrX,18588118,G,C,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.719G>C,ENSP00000369325.3:p.Ser240Thr,Ser240Thr,S240T
4,chrX,18603988,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1064G>A,ENSP00000369325.3:p.Arg355Gln,Arg355Gln,R355Q
5,chrX,18604012,A,G,GRCh38,0.000530,CDKL5,missense_variant,ENST00000379989.6:c.1088A>G,ENSP00000369325.3:p.Asn363Ser,Asn363Ser,N363S
6,chrX,18604366,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1442C>G,ENSP00000369325.3:p.Ser481Cys,Ser481Cys,S481C
7,chrX,18604686,C,T,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.1762C>T,ENSP00000369325.3:p.Pro588Ser,Pro588Ser,P588S
8,chrX,18613214,C,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2215C>G,ENSP00000369325.3:p.Leu739Val,Leu739Val,L739V
9,chrX,18613242,A,G,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2243A>G,ENSP00000369325.3:p.Asn748Ser,Asn748Ser,N748S
10,chrX,18619962,A,C,GRCh38,0.016689,CDKL5,missense_variant,ENST00000379989.6:c.2372A>C,ENSP00000369325.3:p.Gln791Pro,Gln791Pro,Q791P
11,chrX,18628543,G,A,GRCh38,0.000265,CDKL5,missense_variant,ENST00000379989.6:c.2669G>A,ENSP00000369325.3:p.Arg890Gln,Arg890Gln,R890Q

# ====================================== #

# 6 Hector2017

In [ ]:
## 6.1 view data

In [44]:
from IPython.display import display
import pandas as pd

# Load the Excel file and the specified sheet
hector_file_path = "00_data/hector2017.xlsx"
hector_df = pd.read_excel(hector_file_path, sheet_name="Sheet1")

# Display the dataframe using IPython display
display(hector_df)

   Mutation                   Consequence         Source
0      H36R          Benign/Likely benign  PMID_29264392
1      T56M          Benign/Likely benign  PMID_29264392
2      R65Q          Benign/Likely benign  PMID_29264392
3      R80H          Benign/Likely benign  PMID_29264392
4      R80L          Benign/Likely benign  PMID_29264392
..      ...                           ...            ...
68    Y262H  Pathogenic/Likely pathogenic  PMID_29264392
69    L271P  Pathogenic/Likely pathogenic  PMID_29264392
70    R285S  Pathogenic/Likely pathogenic  PMID_29264392
71    T288I  Pathogenic/Likely pathogenic  PMID_29264392
72    C291Y  Pathogenic/Likely pathogenic  PMID_29264392

[73 rows x 3 columns]

# ===================================== #

# 7 Combined dataset (Clinvar, 1kgp & hector2017)

## 7.1 columns for these datasets

In [47]:
!ls 00_data/

1kgp_cdkl5_grch38.xlsx	gnomAD.csv	 protein_change_comparison.xlsx
clinvar_result.txt	gnomAD.xlsx
clinvar_result.xlsx	hector2017.xlsx

## 7.2 sheets name

In [49]:
import pandas as pd

# File paths
clinvar_path = '00_data/clinvar_result.xlsx'
kgp_path = '00_data/1kgp_cdkl5_grch38.xlsx'
hector_path = '00_data/hector2017.xlsx'

# Load and print sheet names
print("Sheets in clinvar_result.xlsx:")
print(pd.ExcelFile(clinvar_path).sheet_names)

print("\nSheets in 1kgp_cdkl5_grch38.xlsx:")
print(pd.ExcelFile(kgp_path).sheet_names)

print("\nSheets in hector2017.xlsx:")
print(pd.ExcelFile(hector_path).sheet_names)

Sheets in clinvar_result.xlsx:
['Sheet1', 'Single_Nucleotide_Variant', 'Missense_Variant', 'CDKL5_Condition', 'CDKL5_missense_only']

Sheets in 1kgp_cdkl5_grch38.xlsx:
['Sheet1', 'missense_only', 'missense_cdkl5_only', 'missense_cdkl5_unique', 'missense_cdkl5_unique_prot_chan']

Sheets in hector2017.xlsx:
['Sheet1']

## 7.3 columns name

In [51]:
import pandas as pd

# File paths
clinvar_path = '00_data/clinvar_result.xlsx'
kgp_path = '00_data/1kgp_cdkl5_grch38.xlsx'
hector_path = '00_data/hector2017.xlsx'

# Load the specific sheets
clinvar_df = pd.read_excel(clinvar_path, sheet_name='CDKL5_missense_only')
kgp_df = pd.read_excel(kgp_path, sheet_name='missense_cdkl5_unique_prot_chan')
hector_df = pd.read_excel(hector_path, sheet_name='Sheet1')

# Display column names
print("Columns in 'CDKL5_missense_only' from clinvar_result.xlsx:")
print(clinvar_df.columns.tolist())

print("\nColumns in 'missense_cdkl5_unique_prot_chan' from 1kgp_cdkl5_grch38.xlsx:")
print(kgp_df.columns.tolist())

print("\nColumns in 'Sheet1' from hector2017.xlsx:")
print(hector_df.columns.tolist())

Columns in 'CDKL5_missense_only' from clinvar_result.xlsx:
['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24']

Columns in 'missense_cdkl5_unique_prot_chan' from 1kgp_cdkl5_grch38.xlsx:
['CHROM', 'POS', 'REF', 'ALT', 'RefGenome', 'AF', 'Gene', 'Consequence', 'HGVSc', 'HGVSp', 'Protein change 3L', 'Protein change']

Columns in 'Sheet1' from hector2017.xlsx:
['Mutation', 'Consequence', 'Source']

## 7.4 Unique and common entries among them

In [53]:
import pandas as pd

# Load datasets
clinvar_df = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_missense_only')
kgp_df = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_cdkl5_unique_prot_chan')
hector_df = pd.read_excel('00_data/hector2017.xlsx', sheet_name='Sheet1')

# Clean and extract relevant sets
clinvar_set = set(clinvar_df['Protein change'].dropna().unique())
kgp_set = set(kgp_df['Protein change'].dropna().unique())
hector_set = set(hector_df['Mutation'].dropna().unique())

# Comparison using ClinVar as reference
kgp_common = kgp_set & clinvar_set
kgp_unique_wrt_clinvar = kgp_set - clinvar_set

hector_common = hector_set & clinvar_set
hector_unique_wrt_clinvar = hector_set - clinvar_set

# Print counts
print("Using ClinVar as reference:")
print(f"ClinVar total entries: {len(clinvar_set)}\n")

print(f"1KGP:")
print(f"  Entries in ClinVar (common): {len(kgp_common)}")
print(f"  Entries NOT in ClinVar (unique): {len(kgp_unique_wrt_clinvar)}\n")

print(f"Hector2017:")
print(f"  Entries in ClinVar (common): {len(hector_common)}")
print(f"  Entries NOT in ClinVar (unique): {len(hector_unique_wrt_clinvar)}")

Using ClinVar as reference:
ClinVar total entries: 120

1KGP:
  Entries in ClinVar (common): 4
  Entries NOT in ClinVar (unique): 8

Hector2017:
  Entries in ClinVar (common): 43
  Entries NOT in ClinVar (unique): 30

## 7.5 Save a new excel sheet contains Clinvar, 1KGP & Hector2017 (unique),

In [54]:
import pandas as pd

# Load data
clinvar_df = pd.read_excel('00_data/clinvar_result.xlsx', sheet_name='CDKL5_missense_only')
kgp_df = pd.read_excel('00_data/1kgp_cdkl5_grch38.xlsx', sheet_name='missense_cdkl5_unique_prot_chan')
hector_df = pd.read_excel('00_data/hector2017.xlsx', sheet_name='Sheet1')

# Extract relevant values
clinvar_set = set(clinvar_df['Protein change'].dropna().unique())
kgp_set = set(kgp_df['Protein change'].dropna().unique())
hector_set = set(hector_df['Mutation'].dropna().unique())

# Unique entries w.r.t. ClinVar
kgp_unique_wrt_clinvar = kgp_set - clinvar_set
hector_unique_wrt_clinvar = hector_set - clinvar_set

# Create filtered DataFrames
kgp_unique_df = kgp_df[kgp_df['Protein change'].isin(kgp_unique_wrt_clinvar)]
hector_unique_df = hector_df[hector_df['Mutation'].isin(hector_unique_wrt_clinvar)]

# Save to Excel
output_path = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
    clinvar_df.to_excel(writer, sheet_name='ClinVar', index=False)
    kgp_unique_df.to_excel(writer, sheet_name='1KGP_unique', index=False)
    hector_unique_df.to_excel(writer, sheet_name='Hector2017_unique', index=False)

print(f"Saved output to '{output_path}' with sheets: ClinVar, 1KGP_unique, Hector2017_unique.")

Saved output to '00_data/clinvar_kgp_hector_unique_summary.xlsx' with sheets: ClinVar, 1KGP_unique, Hector2017_unique.

# =========================== #

# 8 Manually merge three unique datasets 
Now i have manually made a new sheet in the same 'clinvar_kgp_hector_unique_summary.xlsx' file and named the sheet: 'clinvar_1kgp_hector'

In [56]:
import pandas as pd
from IPython.display import display

# Load the merged sheet
merged_df = pd.read_excel('00_data/clinvar_kgp_hector_unique_summary.xlsx', sheet_name='clinvar_1kgp_hector')

# Display the dataframe
display(merged_df)

,Name,Gene(s),Protein change,Condition(s),Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,...,Source,Germline date last evaluated,Germline review status,Somatic clinical impact,Somatic clinical impact date last evaluated,Somatic clinical impact review status,Oncogenicity classification,Oncogenicity date last evaluated,Oncogenicity review status,Unnamed: 24
0,NM_001323289.2(CDKL5):c.320T>A (p.Val107Asp),CDKL5,V107D,CDKL5 disorder,VCV003775037,X,18598005.0,X,18579885.0,3775037.0,...,Clinvar,"Feb 28, 2025",reviewed by expert panel,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NM_001323289.2(CDKL5):c.592G>C (p.Gly198Arg),CDKL5,G198R,CDKL5 disorder,VCV003775036,X,18606111.0,X,18587991.0,3775036.0,...,Clinvar,"Feb 28, 2025",reviewed by expert panel,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NM_001323289.2(CDKL5):c.1468G>A (p.Gly490Arg),CDKL5,G490R,CDKL5 disorder,VCV003775035,X,18622512.0,X,18604392.0,3775035.0,...,Clinvar,"Feb 28, 2025",reviewed by expert panel,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NM_001323289.2(CDKL5):c.226A>G (p.Lys76Glu),CDKL5,K76E,CDKL5 disorder,VCV003602048,X,18593554.0,X,18575434.0,3602048.0,...,Clinvar,"Dec 24, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NM_001323289.2(CDKL5):c.104C>T (p.Thr35Ile),CDKL5,T35I,CDKL5 disorder,VCV003602046,X,18582601.0,X,18564481.0,3602046.0,...,Clinvar,"Dec 24, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,PMID_29264392,CDKL5,G202E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PMID_29264417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,PMID_29264392,CDKL5,P209R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PMID_29264418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,PMID_29264392,CDKL5,G213R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PMID_29264419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,PMID_29264392,CDKL5,R248W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PMID_29264420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,PMID_29264392,CDKL5,Y262H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PMID_29264421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## if any duplication in the 'Protein change' column

In [57]:
import pandas as pd

# Load the sheet
merged_df = pd.read_excel('00_data/clinvar_kgp_hector_unique_summary.xlsx', sheet_name='clinvar_1kgp_hector')

# Print column names
print("Columns in 'clinvar_1kgp_hector':")
print(merged_df.columns.tolist())

Columns in 'clinvar_1kgp_hector':
['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Source', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24']

In [58]:
import pandas as pd

# Load the sheet
merged_df = pd.read_excel('00_data/clinvar_kgp_hector_unique_summary.xlsx', sheet_name='clinvar_1kgp_hector')

# Check duplicates in 'Protein change' column
duplicates = merged_df['Protein change'].duplicated()
num_duplicates = duplicates.sum()

print(f"Number of duplicate entries in 'Protein change': {num_duplicates}")

Number of duplicate entries in 'Protein change': 0

## get allele frequency from gnomAD

## first view the gnomAD sheets & columns 
file: 00_data/gnomAD.xlsx
sheet: 'Protein_Change_Converted'
Column: 'Protein change (One-Letter)'

In [59]:
!ls 00_data/

1kgp_cdkl5_grch38.xlsx			gnomAD.csv
clinvar_kgp_hector_unique_summary.xlsx	gnomAD.xlsx
clinvar_result.txt			hector2017.xlsx
clinvar_result.xlsx			protein_change_comparison.xlsx

In [61]:
import pandas as pd

file_path = '00_data/gnomAD.xlsx'
xls = pd.ExcelFile(file_path)
print("Sheets in gnomAD.xlsx:")
print(xls.sheet_names)

Sheets in gnomAD.xlsx:
['Sheet1', 'Missense_Variant', 'Protein_Change_Converted', 'ClinVar_Classified_Only']

In [62]:
import pandas as pd

file_path = '00_data/gnomAD.xlsx'
sheet_name = 'Protein_Change_Converted'

df = pd.read_excel(file_path, sheet_name=sheet_name)
print(f"Columns in '{sheet_name}':")
print(df.columns.tolist())

Columns in 'Protein_Change_Converted':
['gnomAD ID', 'Chromosome', 'Position', 'rsIDs', 'Reference', 'Alternate', 'Source', 'Filters - exomes', 'Filters - genomes', 'Transcript', 'HGVS Consequence', 'Protein Consequence', 'Transcript Consequence', 'VEP Annotation', 'ClinVar Germline Classification', 'ClinVar Variation ID', 'Flags', 'Allele Count', 'Allele Number', 'Allele Frequency', 'Homozygote Count', 'Hemizygote Count', 'Filters - joint', 'GroupMax FAF group', 'GroupMax FAF frequency', 'cadd', 'revel_max', 'spliceai_ds_max', 'pangolin_largest_ds', 'phylop', 'sift_max', 'polyphen_max', 'Allele Count African/African American', 'Allele Number African/African American', 'Homozygote Count African/African American', 'Hemizygote Count African/African American', 'Allele Count Admixed American', 'Allele Number Admixed American', 'Homozygote Count Admixed American', 'Hemizygote Count Admixed American', 'Allele Count Ashkenazi Jewish', 'Allele Number Ashkenazi Jewish', 'Homozygote Count Ashkenazi Jewish', 'Hemizygote Count Ashkenazi Jewish', 'Allele Count East Asian', 'Allele Number East Asian', 'Homozygote Count East Asian', 'Hemizygote Count East Asian', 'Allele Count European (Finnish)', 'Allele Number European (Finnish)', 'Homozygote Count European (Finnish)', 'Hemizygote Count European (Finnish)', 'Allele Count Middle Eastern', 'Allele Number Middle Eastern', 'Homozygote Count Middle Eastern', 'Hemizygote Count Middle Eastern', 'Allele Count European (non-Finnish)', 'Allele Number European (non-Finnish)', 'Homozygote Count European (non-Finnish)', 'Hemizygote Count European (non-Finnish)', 'Allele Count Amish', 'Allele Number Amish', 'Homozygote Count Amish', 'Hemizygote Count Amish', 'Allele Count South Asian', 'Allele Number South Asian', 'Homozygote Count South Asian', 'Hemizygote Count South Asian', 'Allele Count Remaining', 'Allele Number Remaining', 'Homozygote Count Remaining', 'Hemizygote Count Remaining', 'Protein Consequence (Three-Letter)', 'Protein change (One-Letter)']

## pull gnomAD allele frequency
data: clinvar
file: 00_data/clinvar_kgp_hector_unique_summary.xlsx
sheet: 'clinvar_1kgp_hector'
Protein change column: 'Protein change'
allele frequency column: 'Allele Frequency'

data: gnomAD
file: 00_data/gnomAD.xlsx
sheet: 'Protein_Change_Converted'
Protein change Column: 'Protein change (One-Letter)'

So what i want is:
read clinvar data, sheet and protein change column
then match with the entries found in 'Protein_Change_Converted' sheet of gnomAD data with the column 'Protien change (One-Letter)'

and pull out corresponding 'Allele Frequency'
and save it as a new sheet in the clinvar excel file with proper name

In [63]:
import pandas as pd

# File paths
clinvar_file = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
gnomad_file = '00_data/gnomAD.xlsx'

# Read ClinVar data
clinvar_df = pd.read_excel(clinvar_file, sheet_name='clinvar_1kgp_hector')
# Column with protein changes (one-letter code)
clinvar_col = 'Protein change'

# Read gnomAD data
gnomad_df = pd.read_excel(gnomad_file, sheet_name='Protein_Change_Converted')
gnomad_protein_col = 'Protein change (One-Letter)'
gnomad_af_col = 'Allele Frequency'

# Merge ClinVar with gnomAD on protein change (one-letter code)
merged_df = pd.merge(
    clinvar_df,
    gnomad_df[[gnomad_protein_col, gnomad_af_col]],
    left_on=clinvar_col,
    right_on=gnomad_protein_col,
    how='left'
)

# Rename the gnomAD Allele Frequency column for clarity
merged_df.rename(columns={gnomad_af_col: 'gnomAD Allele Frequency'}, inplace=True)

# Drop the redundant gnomAD protein change column after merge
merged_df.drop(columns=[gnomad_protein_col], inplace=True)

# Save to a new sheet in the same ClinVar Excel file
with pd.ExcelWriter(clinvar_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    merged_df.to_excel(writer, sheet_name='clinvar_1kgp_hector_gaf', index=False)

print("Saved merged data with gnomAD Allele Frequency to sheet 'clinvar_1kgp_hector_gaf'.")

Saved merged data with gnomAD Allele Frequency to sheet 'clinvar_1kgp_hector_gaf'.

In [ ]:
## view the dataset

In [65]:
import pandas as pd

clinvar_file = '00_data/clinvar_kgp_hector_unique_summary.xlsx'

# Load the new sheet
df_new = pd.read_excel(clinvar_file, sheet_name='clinvar_1kgp_hector_gaf')

# Display the dataframe nicely in IPython
from IPython.display import display
display(df_new.head(10))

,Name,Gene(s),Protein change,Condition(s),Accession,GRCh37Chromosome,GRCh37Location,GRCh38Chromosome,GRCh38Location,VariationID,...,Germline date last evaluated,Germline review status,Somatic clinical impact,Somatic clinical impact date last evaluated,Somatic clinical impact review status,Oncogenicity classification,Oncogenicity date last evaluated,Oncogenicity review status,Unnamed: 24,gnomAD Allele Frequency
0,NM_001323289.2(CDKL5):c.320T>A (p.Val107Asp),CDKL5,V107D,CDKL5 disorder,VCV003775037,X,18598005.0,X,18579885.0,3775037.0,...,"Feb 28, 2025",reviewed by expert panel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NM_001323289.2(CDKL5):c.592G>C (p.Gly198Arg),CDKL5,G198R,CDKL5 disorder,VCV003775036,X,18606111.0,X,18587991.0,3775036.0,...,"Feb 28, 2025",reviewed by expert panel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NM_001323289.2(CDKL5):c.1468G>A (p.Gly490Arg),CDKL5,G490R,CDKL5 disorder,VCV003775035,X,18622512.0,X,18604392.0,3775035.0,...,"Feb 28, 2025",reviewed by expert panel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000002
3,NM_001323289.2(CDKL5):c.226A>G (p.Lys76Glu),CDKL5,K76E,CDKL5 disorder,VCV003602048,X,18593554.0,X,18575434.0,3602048.0,...,"Dec 24, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NM_001323289.2(CDKL5):c.104C>T (p.Thr35Ile),CDKL5,T35I,CDKL5 disorder,VCV003602046,X,18582601.0,X,18564481.0,3602046.0,...,"Dec 24, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
5,NM_001323289.2(CDKL5):c.551T>A (p.Leu184His),CDKL5,L184H,CDKL5 disorder,VCV003602045,X,18602470.0,X,18584350.0,3602045.0,...,"Dec 23, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NM_001323289.2(CDKL5):c.530A>C (p.Tyr177Ser),CDKL5,Y177S,CDKL5 disorder,VCV003602044,X,18602449.0,X,18584329.0,3602044.0,...,"Dec 23, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NM_001323289.2(CDKL5):c.464G>A (p.Gly155Asp),CDKL5,G155D,CDKL5 disorder,VCV003602043,X,18602383.0,X,18584263.0,3602043.0,...,"Dec 23, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NM_001323289.2(CDKL5):c.607G>A (p.Glu203Lys),CDKL5,E203K,CDKL5 disorder,VCV003602042,X,18606126.0,X,18588006.0,3602042.0,...,"Dec 20, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NM_001323289.2(CDKL5):c.521C>A (p.Thr174Asn),CDKL5,T174N,CDKL5 disorder,VCV003602018,X,18602440.0,X,18584320.0,3602018.0,...,"Dec 17, 2024","criteria provided, single submitter",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [ ]:
## how many gnomAD AF and NaN

In [66]:
# Count non-NaN values
non_nan_count = df_new['gnomAD Allele Frequency'].notna().sum()

# Count NaN values
nan_count = df_new['gnomAD Allele Frequency'].isna().sum()

print(f"Number of non-NaN entries: {non_nan_count}")
print(f"Number of NaN entries: {nan_count}")

Number of non-NaN entries: 73
Number of NaN entries: 85

In [67]:
print(df_new.columns.tolist())

['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Source', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24', 'gnomAD Allele Frequency']

In [ ]:
## value counts

In [70]:
from IPython.display import display

for col in ['Variant type', 'Molecular consequence', 'Germline classification']:
    print(f"Value counts for '{col}':")
    counts = df_new[col].value_counts(dropna=False)
    display(counts.to_frame(name='Count'))
    print(f"Total entries in '{col}': {len(df_new[col])}\n")

Value counts for 'Variant type':

                           Count
Variant type
single nucleotide variant    120
NaN                           38

Total entries in 'Variant type': 158

Value counts for 'Molecular consequence':

                       Count
Molecular consequence
missense variant         128
NaN                       30

Total entries in 'Molecular consequence': 158

Value counts for 'Germline classification':

                                              Count
Germline classification
Uncertain significance                           43
Pathogenic/Likely pathogenic                     26
Likely pathogenic                                22
Benign                                           20
Benign/Likely benign                             15
Conflicting classifications of pathogenicity     13
Likely benign                                    10
Pathogenic                                        9

Total entries in 'Germline classification': 158

## 'Protein change' column sanity check with Uniprot seq
'Protein change' column represents 
'one_letter_code_of_wild_type_amino_acid-position-one_letter_code_of_mutant_amino_acid''
for example 'V107D'

here 
V:one_letter_code_of_wild_type_amino_acid
107:position
D:one_letter_code_of_mutant_amino_acid

now cdkl5 uniprot id is: 'O76039'
pull out amino acid sequence using the uniprot id

then match with the 
one_letter_code_of_wild_type_amino_acid
and 
position

and print summary of the result

In [71]:
import requests
import pandas as pd

# Step 1: Fetch CDKL5 sequence from UniProt (FASTA format)
uniprot_id = "O76039"
url = f"https://www.uniprot.org/uniprot/{uniprot_id}.fasta"
response = requests.get(url)
fasta_text = response.text

# Parse FASTA sequence (skip header line)
lines = fasta_text.split('\n')
sequence = ''.join(line.strip() for line in lines if not line.startswith('>'))

print(f"Length of CDKL5 sequence: {len(sequence)}")

# Step 2: Load your data with the 'Protein change' column
file_path = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf'

df = pd.read_excel(file_path, sheet_name=sheet_name)

# Step 3: Extract wild type AA, position, mutant AA from 'Protein change'
def parse_protein_change(pc):
    # Example format: V107D
    if isinstance(pc, str) and len(pc) >= 3:
        wt = pc[0]
        mut = pc[-1]
        pos = pc[1:-1]
        if pos.isdigit():
            return wt, int(pos), mut
    return None, None, None

df[['wt_aa', 'pos', 'mut_aa']] = df['Protein change'].apply(
    lambda x: pd.Series(parse_protein_change(x))
)

# Step 4: Check match against UniProt sequence
def check_match(row):
    wt = row['wt_aa']
    pos = row['pos']
    if wt is None or pos is None or pos > len(sequence) or pos < 1:
        return 'Invalid'
    # UniProt sequence is 1-based index, python 0-based
    seq_aa = sequence[pos-1]
    return 'Match' if seq_aa == wt else f'Mismatch (Seq: {seq_aa})'

df['match_status'] = df.apply(check_match, axis=1)

# Step 5: Summary
summary = df['match_status'].value_counts()
print(summary)

# Optional: print mismatch rows to inspect
print("\nMismatches:")
print(df[df['match_status'].str.contains('Mismatch')][['Protein change', 'wt_aa', 'pos', 'mut_aa', 'match_status']])

Length of CDKL5 sequence: 960
match_status
Match                156
Mismatch (Seq: H)      1
Mismatch (Seq: D)      1
Name: count, dtype: int64

Mismatches:
    Protein change wt_aa  pos mut_aa       match_status
147          Y145H     Y  145      H  Mismatch (Seq: H)
149          A153G     A  153      G  Mismatch (Seq: D)

In [73]:
import pandas as pd

# File path and sheet names
file_path = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
input_sheet = 'clinvar_1kgp_hector_gaf'
output_sheet = 'clinvar_1kgp_hector_gaf_final'

# Load the data
df = pd.read_excel(file_path, sheet_name=input_sheet)

# Remove mismatches based on exact 'Protein change'
mismatches = ['Y145H', 'A153G']
df_filtered = df[~df['Protein change'].isin(mismatches)].copy()

# Copy 'Protein change' column to new column 'Mutation'
df_filtered['Mutation'] = df_filtered['Protein change']

# Extract wild, position, and mutant from 'Mutation'
df_filtered['wild'] = df_filtered['Mutation'].str.extract(r'^([A-Z])')
df_filtered['position'] = df_filtered['Mutation'].str.extract(r'(\d+)').astype(int)
df_filtered['mutant'] = df_filtered['Mutation'].str.extract(r'([A-Z])$')

# Sort by position
df_filtered = df_filtered.sort_values(by='position')

# Save to a new sheet
with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df_filtered.to_excel(writer, sheet_name=output_sheet, index=False)

print(f"✅ Final dataset saved to sheet '{output_sheet}' in '{file_path}'.")

✅ Final dataset saved to sheet 'clinvar_1kgp_hector_gaf_final' in '00_data/clinvar_kgp_hector_unique_summary.xlsx'.

In [ ]:
## columns in final sheet

In [74]:
import pandas as pd

# File path and sheet name
file_path = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf_final'

# Load the sheet
df_final = pd.read_excel(file_path, sheet_name=sheet_name)

# Display column names
print("✅ Columns in the final sheet:")
print(df_final.columns.tolist())

✅ Columns in the final sheet:
['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Source', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24', 'gnomAD Allele Frequency', 'Mutation', 'wild', 'position', 'mutant']

In [ ]:
## Value count | NaN-non-NaN values for AF | AF range

In [78]:
import pandas as pd
import numpy as np
from IPython.display import display

# File path and sheet name
file_path = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf_final'

# Load data
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Variant type value counts
print(f"✅ Variant type (Total: {df['Variant type'].notna().sum()}):")
display(df['Variant type'].value_counts(dropna=False).to_frame(name='count'))

# Molecular consequence value counts
print(f"\n✅ Molecular consequence (Total: {df['Molecular consequence'].notna().sum()}):")
display(df['Molecular consequence'].value_counts(dropna=False).to_frame(name='count'))

# Germline classification value counts
print(f"\n✅ Germline classification (Total: {df['Germline classification'].notna().sum()}):")
display(df['Germline classification'].value_counts(dropna=False).to_frame(name='count'))

# gnomAD Allele Frequency NaN/non-NaN
non_nan_gaf = df['gnomAD Allele Frequency'].notna().sum()
nan_gaf = df['gnomAD Allele Frequency'].isna().sum()
print(f"\n✅ gnomAD Allele Frequency:")
print(f"  Non-NaN values: {non_nan_gaf}")
print(f"  NaN values: {nan_gaf}")

# Add gaf_filled column where NaNs are replaced with 0
df['gaf_filled'] = df['gnomAD Allele Frequency'].fillna(0)

# Range of gnomAD Allele Frequency by Germline classification
#print("\n✅ gnomAD Allele Frequency range by Germline classification (NaN → 0):")
#display(df.groupby('Germline classification')['gaf_filled'].agg(['min', 'max']))

✅ Variant type (Total: 120):

                           count
Variant type
single nucleotide variant    120
NaN                           36

✅ Molecular consequence (Total: 128):

                       count
Molecular consequence
missense variant         128
NaN                       28

✅ Germline classification (Total: 156):

                                              count
Germline classification
Uncertain significance                           43
Pathogenic/Likely pathogenic                     24
Likely pathogenic                                22
Benign                                           20
Benign/Likely benign                             15
Conflicting classifications of pathogenicity     13
Likely benign                                    10
Pathogenic                                        9

✅ gnomAD Allele Frequency:
  Non-NaN values: 73
  NaN values: 83

In [77]:
import pandas as pd
from IPython.display import display

# File path and sheet name
file_path = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf_final'

# Load data
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Fill NaN gAF with 0 for analysis
df['gaf_filled'] = df['gnomAD Allele Frequency'].fillna(0)

# Group by 'Germline classification' and calculate count, min, and max
summary = df.groupby('Germline classification').agg(
    count=('Germline classification', 'count'),
    min_gaf=('gaf_filled', 'min'),
    max_gaf=('gaf_filled', 'max')
).sort_values(by='count', ascending=False)

# Display summary
print("✅ gnomAD Allele Frequency stats by Germline classification (NaN → 0):")
display(summary)

✅ gnomAD Allele Frequency stats by Germline classification (NaN → 0):

,count,min_gaf,max_gaf
Germline classification,,,
Uncertain significance,43,0.000000e+00,9.106661e-06
Pathogenic/Likely pathogenic,24,0.000000e+00,0.000000e+00
Likely pathogenic,22,0.000000e+00,8.256234e-07
Benign,20,8.275823e-07,4.387166e-02
Benign/Likely benign,15,8.266034e-07,2.958245e-04
Conflicting classifications of pathogenicity,13,0.000000e+00,2.561751e-05
Likely benign,10,8.253277e-07,6.248724e-05
Pathogenic,9,0.000000e+00,0.000000e+00

## one final check 'Mutation' old vs new unique common

In [81]:
import pandas as pd

# Paths and sheets
old_file = '00_data/01_cdkl5_clinvar_gaf_1kgp_hctr_comb_unq_af_old.xlsx'
old_sheet = 'Sheet1_with_AF'  # use actual sheet name, or read first sheet dynamically if unsure

current_file = '00_data/clinvar_kgp_hector_unique_summary.xlsx'
current_sheet = 'clinvar_1kgp_hector_gaf_final'

# Load data
df_old = pd.read_excel(old_file, sheet_name=old_sheet)
df_current = pd.read_excel(current_file, sheet_name=current_sheet)

# Extract 'Mutation' columns as sets
mutations_old = set(df_old['mutation'].dropna().unique())
mutations_current = set(df_current['Mutation'].dropna().unique())

# Compare
common = mutations_current.intersection(mutations_old)
unique_current = mutations_current.difference(mutations_old)
unique_old = mutations_old.difference(mutations_current)

# Print results
print(f"Using current file as reference:")
print(f"Total mutations in current file: {len(mutations_current)}")
print(f"Entries common with old file: {len(common)}")
print(f"Entries unique to current file: {len(unique_current)}")
print(f"Entries unique to old file: {len(unique_old)}")

Using current file as reference:
Total mutations in current file: 156
Entries common with old file: 156
Entries unique to current file: 0
Entries unique to old file: 0

# 9 final value count

In [5]:
import pandas as pd

# Path to your Excel file
file_path = '/project/ealexov/compbio/shamrat/250519_energy/00_data/clinvar_kgp_hector_unique_summary.xlsx'

# 01 Load Excel file and print sheet names
excel_file = pd.ExcelFile(file_path)
print(excel_file.sheet_names)

# 02 Load the specific sheet
sheet_name = 'clinvar_1kgp_hector_gaf_final'
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Print column names
print(df.columns.tolist())

# 03 Get value counts for 'Germline classification'
value_counts = df['Germline classification'].value_counts(dropna=False)
print(value_counts)

# Print total count (including NaN if any)
total_count = df['Germline classification'].shape[0]
print(f"\nTotal count: {total_count}")

['ClinVar', '1KGP_unique', 'Hector2017_unique', 'clinvar_1kgp_hector', 'clinvar_1kgp_hector_gaf', 'clinvar_1kgp_hector_gaf_final']
['Name', 'Gene(s)', 'Protein change', 'Condition(s)', 'Accession', 'GRCh37Chromosome', 'GRCh37Location', 'GRCh38Chromosome', 'GRCh38Location', 'VariationID', 'AlleleID(s)', 'dbSNP ID', 'Canonical SPDI', 'Variant type', 'Molecular consequence', 'Germline classification', 'Source', 'Germline date last evaluated', 'Germline review status', 'Somatic clinical impact', 'Somatic clinical impact date last evaluated', 'Somatic clinical impact review status', 'Oncogenicity classification', 'Oncogenicity date last evaluated', 'Oncogenicity review status', 'Unnamed: 24', 'gnomAD Allele Frequency', 'Mutation', 'wild', 'position', 'mutant']
Germline classification
Uncertain significance                          43
Pathogenic/Likely pathogenic                    24
Likely pathogenic                               22
Benign                                          20
Benign/Likely benign                            15
Conflicting classifications of pathogenicity    13
Likely benign                                   10
Pathogenic                                       9
Name: count, dtype: int64

Total count: 156

In [2]:
import pandas as pd
from IPython.display import display

# Path to your Excel file
file_path = '/project/ealexov/compbio/shamrat/250519_energy/00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf_final'

# Load sheet
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Filter for position range 1-302
df_1_302 = df[(df['position'] >= 1) & (df['position'] <= 302)]

# Value counts for 'Germline classification', sorted alphabetically by index
value_counts = df_1_302['Germline classification'].value_counts(dropna=False).sort_index()

# Convert to DataFrame for nice display
value_counts_df = value_counts.rename_axis('Germline classification').reset_index(name='count')

display(value_counts_df)

# Display total count as well
print(f"\nTotal count (positions 1-302): {df_1_302.shape[0]}")

                        Germline classification  count
0                                        Benign      4
1                          Benign/Likely benign     12
2  Conflicting classifications of pathogenicity     10
3                                 Likely benign      1
4                             Likely pathogenic     22
5                                    Pathogenic      9
6                  Pathogenic/Likely pathogenic     24
7                        Uncertain significance     30

Total count (positions 1-302): 112

In [3]:
import pandas as pd
from IPython.display import display

# Path to your Excel file
file_path = '/project/ealexov/compbio/shamrat/250519_energy/00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf_final'

# Load sheet
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Filter for position range 1-895
df_1_895 = df[(df['position'] >= 1) & (df['position'] <= 895)]

# Value counts for 'Germline classification', sorted alphabetically by index
value_counts = df_1_895['Germline classification'].value_counts(dropna=False).sort_index()

# Convert to DataFrame for nice display
value_counts_df = value_counts.rename_axis('Germline classification').reset_index(name='count')

display(value_counts_df)

# Display total count as well
print(f"\nTotal count (positions 1-895): {df_1_895.shape[0]}")

                        Germline classification  count
0                                        Benign     20
1                          Benign/Likely benign     15
2  Conflicting classifications of pathogenicity     13
3                                 Likely benign     10
4                             Likely pathogenic     22
5                                    Pathogenic      9
6                  Pathogenic/Likely pathogenic     24
7                        Uncertain significance     43

Total count (positions 1-895): 156

In [4]:
import pandas as pd
from IPython.display import display

# Path to your Excel file
file_path = '/project/ealexov/compbio/shamrat/250519_energy/00_data/clinvar_kgp_hector_unique_summary.xlsx'
sheet_name = 'clinvar_1kgp_hector_gaf_final'

# Load sheet
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Filter for position ranges
df_1_302 = df[(df['position'] >= 1) & (df['position'] <= 302)]
df_1_895 = df[(df['position'] >= 1) & (df['position'] <= 895)]

# Get value counts, sorted alphabetically
vc_1_302 = df_1_302['Germline classification'].value_counts(dropna=False).sort_index()
vc_1_895 = df_1_895['Germline classification'].value_counts(dropna=False).sort_index()

# Combine in a single DataFrame
counts_df = pd.DataFrame({
    'Germline classification': vc_1_302.index,
    'count_1_302': vc_1_302.values,
}).set_index('Germline classification')

counts_df['count_1_895'] = vc_1_895

# Reset index for display
counts_df = counts_df.reset_index()

display(counts_df)

# Optionally, print total counts for each range
print(f"Total count (positions 1-302): {df_1_302.shape[0]}")
print(f"Total count (positions 1-895): {df_1_895.shape[0]}")

                        Germline classification  count_1_302  count_1_895
0                                        Benign            4           20
1                          Benign/Likely benign           12           15
2  Conflicting classifications of pathogenicity           10           13
3                                 Likely benign            1           10
4                             Likely pathogenic           22           22
5                                    Pathogenic            9            9
6                  Pathogenic/Likely pathogenic           24           24
7                        Uncertain significance           30           43

Total count (positions 1-302): 112
Total count (positions 1-895): 156